### PR TITLE
[html] Fix building [LFS enabled]

### PR DESCRIPTION
**Pull request by krzyc**
Add missing icudtl.dat for linux
Change CEF related dir variables in CMakeLists.txt

### CODE REVIEW

**Comment by Julusian** [comment]
@krzyc how are you building the linux version? I am still getting boost errors when trying to do so

**Comment by krzyc** [comment]
You need boost 1.66. I have compiled boost and copied .so files to dependencies64/boost/stage/lib/linux and then modified some CMake path parameters to use them. @ronag Should boost 1.66 linux binaries be included in git repo?

**Comment by Julusian** [comment]
Ah ok, I suspected you might have done that. Wanted to check before I did it myself though.
Yeah, @k0d is working on solving that issue I believe.

**Comment by ronag** [comment]
kOd was working on it today. Should be pushed tomorrow.

**Comment by ronag** [comment]
We’re moving away from having dependencies in the repo and I stead pulling them through Docker build scripts.

**Pull request merged**
