### PR TITLE
Add options to build against system-installed components

### PR DESCRIPTION
**Pull request by dimitry-ishenko**
This series is now complete with the exception of CEF, which I will deal with separately at a later time. The idea is similar to what I did for the Client -- if you don't pass any options, the build process remains the same.

I added options to individually disable some of the modules:

BUILD_MODULE_BLUEFISH (Windows only)
BUILD_MODULE_DECKLINK
BUILD_MODULE_HTML
BUILD_MODULE_PSD
BUILD_MODULE_FLASH (Windows only)
BUILD_MODULE_NEWTEK (Windows only)

To disable, for example, the html module, add this to CMake command: cmake -DBUILD_MODULE_HTML=OFF

I've added the following options to compile against system-installed libraries:

USE_SYSTEM_BOOST
USE_SYSTEM_FFMPEG
USE_SYSTEM_TBB
USE_SYSTEM_GLEW
USE_SYSTEM_FREETYPE
USE_SYSTEM_FREEIMAGE
USE_SYSTEM_OPENAL
USE_SYSTEM_SFML
USE_SYSTEM_GTEST
USE_SYSTEM_FONTS

To enable a given option pass it to CMake command, for example: cmake -DUSE_SYSTEM_BOOST=ON -DUSE_SYSTEM_FFMPEG=ON

Also added system-build-linux.sh script.

### CODE REVIEW

**Comment by dimitry-ishenko** [comment]
@HellGore or anyone, are you guys still planning to merge this? If not, I will close this pull request, as it's been bit rotting for a few months now

**Comment by HellGore** [comment]
I don't think you should close it, it may be merged at some point. I still think it is a good idea to provide the possibility.

**Comment by dimitry-ishenko** [comment]
FYI, I've successfully compiled the server without PSD and HTML modules and built against my system libraries (Gentoo Linux) and have been running it as a backup server since November last year. No problems so far.

**Comment by dimitry-ishenko** [comment]
Sorry, didn't mean to close :)

**Comment by dimitry-ishenko** [comment]
I'll let it sit for a while longer. When you are ready to look at it, holler at me and I can rebase, if needed.
I know you guys are busy with other stuff, so if there is any testing or whatever I can do speed this up, lemme know. Thank you

**Comment by sesse** [comment]
I tried ./system-build-linux.sh, but seemingly Debian doesn't have SFML CMake files, even though it has SFML. Is this something the package is supposed to be shipping? I didn't see this in my locally-hacked variant. Google Test has a similar issue, although there, one should actually compile the library oneself as per upstream's requests (see the upstream documentation).

**Comment by dimitry-ishenko** [comment]
@sesse you probably need *-dev packages for this. Try installing libsfml-dev and libgtest-dev

**Comment by dimitry-ishenko** [comment]
I will need to rebase again, as @HellGore just nuked asmlib, which was used in many CMake files

**Comment by sesse** [comment]
Both are already installed.

**Comment by sesse** [comment]
(Granted, libgtest-dev is obsoleted by googletest, but it doesn't matter for this.)

**Comment by mauricev78** [comment]
suddenly i don't feel stupid ;)

i have te same experience as sesse. also tried to install libsfml-dev 
no result

ls
maurice

**Comment by dimitry-ishenko** [comment]
Oh... it looks like libsfml-dev does include the needed CMake file (according to [this](https://packages.debian.org/jessie/amd64/libsfml-dev/filelist), 5th line from the bottom) but it's in the wrong place. Try copying `/usr/share/SFML/cmake/Modules/FindSFML.cmake` to `/usr/share/cmake/Modules/FindSFML.cmake`

**Comment by dimitry-ishenko** [comment]
@sesse what's the problem with google test? Mine doesn't have a CMake file either, but it doesn't seem to be a problem

**Comment by sesse** [comment]
The right path for my case was /usr/share/cmake-3.7/Modules/FindSFML.cmake, but indeed, that helped for SFML. It's not a proper long-term solution, though; I guess the simplest thing is just shipping FindSFML.cmake in CasparCG.

As for Google Test, upstream recommends to simply not ship a precompiled version (presumably because the result is so dependent on compiler flags, which vary from project to project), and as such, Debian doesn't do it. Compiling it is a matter of finding Google Test and compiling gtest-all.cc as part of your local project (I believe CMake calls this a “convenience library”), which is fairly easy in regular make, but I couldn't figure out how to get to work in CMake.

**Comment by dimitry-ishenko** [comment]
> The right path for my case was /usr/share/cmake-3.7/Modules/FindSFML.cmake

Oh right, you are on Debian. They are probably still using CMake 2.8?...

> I guess the simplest thing is just shipping FindSFML.cmake in CasparCG

Either that or you can also set the `CMAKE_MODULE_PATH` variable when running CMake to specify additional paths to look for modules.

> As for Google Test ... I couldn't figure out how to get to work in CMake.

Maybe try setting `GTEST_ROOT` to the path of your locally compiled GTest?...

In summary, try something like this:

    CMAKE_MODULE_PATH="/usr/share/SFML/cmake/Modules/FindSFML.cmake" GTEST_ROOT="/path/to/your/local/GTest" ./system-build-linux.sh

**Comment by sesse** [comment]
>> The right path for my case was /usr/share/cmake-3.7/Modules/FindSFML.cmake
> Oh right, you are on Debian. They are probably still using CMake 2.8?...

Why would CMake 2.8 search in /usr/share/cmake-3.7? Debian unstable is using CMake 3.7.

>> I guess the simplest thing is just shipping FindSFML.cmake in CasparCG
> Either that or you can also set the CMAKE_MODULE_PATH variable when running CMake to specify additional paths to look for modules.

It sounds pretty wrong to have to set CMAKE_MODULE_PATH to find something that's supposed to find SFML, though. :-) But yes, it's a workaround.

> Maybe try setting GTEST_ROOT to the path of your locally compiled GTest?...

But again, I don't have a locally compiled Google Test, and I'm not supposed to, since I can't know ahead-of-time what compile flags it's supposed to be compiled with for each project using it. That is the responsibility of the project using it. (Yes, Google Test is special in this regard. See https://www.apt-browse.org/browse/ubuntu/trusty/main/all/libgtest-dev/1.6.0-1ubuntu6/file/usr/share/doc/libgtest-dev/README.Debian)

> CMAKE_MODULE_PATH="/usr/share/SFML/cmake/Modules/FindSFML.cmake" GTEST_ROOT="/path/to/your/local/GTest" ./system-build-linux.sh

Just to verify, I ran with GTEST_ROOT=/usr/src/googletest/googletest, and it didn't find anything, since there is no prebuilt shared library.

**Comment by dimitry-ishenko** [comment]
> Why would CMake 2.8 search in /usr/share/cmake-3.7? Debian unstable is using CMake 3.7.

OK, forget what I said. I thought you were on Debian stable.

> It sounds pretty wrong to have to set CMAKE_MODULE_PATH to find something that's supposed to find SFML, though. :-) But yes, it's a workaround.

What's really wrong is that libsfml-dev does not put it in the right place. I don't know enough about Debian to know why it does that. On my system (Gentoo) the file gets dropped in the right place for CMake to find it.

> But again, I don't have a locally compiled Google Test, and I'm not supposed to...

For some reason I thought that's what you were trying to do... Well, in that case just use the one shipped with CasparCG. You can just edit the `system-build-linux.sh` and turn off the `USE_SYSTEM_GTEST` variable.

**Comment by sesse** [comment]
> Well, in that case just use the one shipped with CasparCG.

Again: You _cannot_ and _should not_ ship a precompiled Google Test. CasparCG should not, Debian should not. It is the job of CasparCG's build system to compile Google Test on-the-fly with the correct flags.

**Comment by dimitry-ishenko** [comment]
> Again: You cannot and should not ship a precompiled Google Test. CasparCG should not, Debian should not. It is the job of CasparCG's build system to compile Google Test on-the-fly with the correct flags.

Nah... They just say it's "not recommended." I am too lazy to read the whole thing, but it's something to do with the ODR. Since the CasparCG build system controls the compiler flags, it should be fine.

Anyway, I don't think itsa big deal. On my system I am using system-wide gtest with my own projects and with CasparCG and never had any problems.

**Comment by sesse** [comment]
> Nah... They just say it's "not recommended."

Well, OK, so your position is that since Gentoo ignores upstream's explicit recommendation, it surely doesn't matter and other distributions should just follow suit?

> I am too lazy to read the whole thing, but it's something to do with the ODR. Since the CasparCG build system controls the compiler flags, it should be fine.

You mean the CasparCG build system controls the compiler flags of the prebuilt libgtest? No, it really doesn't. Consider Debug versus RelWithDebOpt mode, for instance; those will result in different compiler flags, potentially requiring different libgtest compiles.

> Anyway, I don't think itsa big deal. On my system I am using system-wide gtest with my own projects and with CasparCG and never had any problems.

Sure, and equally, you can also write a few bytes past the end of most buffers without seeing crashes in practice. But it's not legal C++, and it _will_ break in hard-to-debug ways sooner or later.

In any case, my interest in this PR started specifically because the prebuilt libgtest didn't work on my system, so saying “well, just use the prebuilt one” doesn't really solve my problem :-)

**Comment by dimitry-ishenko** [comment]
Wasn't really trying to go on with the argument. I was just trying to help you out with your problem, which obviously didn't work out too well. So, I will just wish you best of luck and go on with my business.

**Comment by mauricev78** [comment]
Hi Dimitri 

i must say i am still interesting in building against ffmpeg though!

ls
Muarice

**Comment by dimitry-ishenko** [comment]
@mauricev78 you can edit the `system-build-linux.sh` script and manually turn on or off the `USE_SYSTEM_...` variables to tell it which system libraries to use.

**Comment by sesse** [comment]
An issue when linking against system Boost: -D_GLIBCXX_USE_CXX11_ABI=0 causes linker errors if Boost isn't also built against it. (It's a suboptimal setting for a C++11 application such as CasparCG, too.)

**Comment by mauricev78** [comment]
hi dimitri i builded FFMPEG from source with this options

`PATH="$HOME/bin:$PATH" PKG_CONFIG_PATH="$HOME/ffmpeg_build/lib/pkgconfig" ./configure --prefix="$HOME/ffmpeg_build" --pkg-config-flags="--static" --extra-cflags="-I$HOME/ffmpeg_build/include" --extra-ldflags="-L$HOME/ffmpeg_build/lib" --bindir="$HOME/bin" --enable-gpl --enable-libass --enable-libfdk-aac --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-nonfree --enable-libsnappy`

running `system-build-linux.sh` i get.

```
Cleaning...
Running cmake..
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found Git: /usr/bin/git (found version "1.9.1") 
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.26") 
-- checking for module 'libavcodec'
--   package 'libavcodec' not found
-- checking for module 'libavfilter'
--   package 'libavfilter' not found
-- checking for module 'libavformat'
--   package 'libavformat' not found
-- checking for module 'libavdevice'
--   package 'libavdevice' not found
-- checking for module 'libavresample'
--   package 'libavresample' not found
-- checking for module 'libavutil'
--   package 'libavutil' not found
-- checking for module 'libswresample'
--   package 'libswresample' not found
-- checking for module 'libswscale'
--   package 'libswscale' not found
-- checking for module 'libpostproc'
--   package 'libpostproc' not found
CMake Error at /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
  Could NOT find FFmpeg (missing: FFmpeg_LIBRARIES FFmpeg_INCLUDE_DIRS
  avcodec_LIBRARIES avcodec_INCLUDE_DIRS avdevice_LIBRARIES
  avdevice_INCLUDE_DIRS avfilter_LIBRARIES avfilter_INCLUDE_DIRS
  avformat_LIBRARIES avformat_INCLUDE_DIRS avutil_LIBRARIES
  avutil_INCLUDE_DIRS postproc_LIBRARIES postproc_INCLUDE_DIRS
  swresample_LIBRARIES swresample_INCLUDE_DIRS swscale_LIBRARIES
  swscale_INCLUDE_DIRS)
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:315 (_FPHSA_FAILURE_MESSAGE)
  CMake/FindFFmpeg.cmake:151 (find_package_handle_standard_args)
  CMakeLists.txt:130 (find_package)


-- Configuring incomplete, errors occurred!
```
sorry if this is a NOOB question i am a C++ beginner ;(

but i am sure  i builded FFMPEG in the wrong place but what is the right place ??

**Comment by sesse** [comment]
I need this patch to be able to compile against Boost 1.63; evidently, they introduced new bugs. They're not CasparCG's fault as I understand it, but the workaround is simple enough, so would you consider including it in your PR?

```diff
--- a/common/log.cpp
+++ b/common/log.cpp
@@ -212,7 +212,9 @@ std::shared_ptr<void> add_preformatted_line_sink(std::function<void(std::string
        {
                std::function<void(std::string line)> formatted_line_sink_;
        public:
-               sink_backend(std::function<void(std::string line)> formatted_line_sink)
+               // The dummy parameter is to work around a bug in newer Boost.Log, where single-argument
+               // constructor forwarders are not recognized unless the parameter uses Boost.Parameter.
+               sink_backend(std::function<void(std::string line)> formatted_line_sink, int)
                        : formatted_line_sink_(std::move(formatted_line_sink))
                {
                }
@@ -232,7 +234,7 @@ std::shared_ptr<void> add_preformatted_line_sink(std::function<void(std::string
 
        typedef boost::log::sinks::synchronous_sink<sink_backend> sink_type;
 
-       auto sink = boost::make_shared<sink_type>(std::move(formatted_line_sink));
+       auto sink = boost::make_shared<sink_type>(std::move(formatted_line_sink), 0);
        bool print_all_characters = true;
 
        sink->set_formatter(boost::bind(&my_formatter<boost::log::formatting_ostream>, print_all_characters, _1, _2));
```

**Comment by sesse** [comment]
It seems that newer OpenAL and newer tbbmalloc have some sort of coexistence issue, causing random crashes on startup. The solution is just to get rid of tbbmalloc; it's already not used on Windows, and it doesn't seem like CasparCG actually has a lot of allocations going on from multiple threads anyway.

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 1ce4329f7..6039bef6b 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -66,7 +66,7 @@ else()
        if(MSVC)
                set(TBB_LIBRARIES optimized tbb debug tbb_debug)
        else()
-               set(TBB_LIBRARIES tbb tbbmalloc tbbmalloc_proxy)
+               set(TBB_LIBRARIES tbb)
        endif()
        set(TBB_BIN_DIR                         "${DEPENDENCIES_FOLDER}/tbb/bin/${PLATFORM_FOLDER_NAME}")
        link_directories("${DEPENDENCIES_FOLDER}/tbb/lib/${PLATFORM_FOLDER_NAME}")
--- a/common/CMakeLists.txt
+++ b/common/CMakeLists.txt
@@ -112,7 +112,7 @@ source_group(sources\\os os/*)
 
 target_link_libraries(common
        "${ASMLIB_LIBRARIES}"
-       "${TBB_LIBRARIES}"
+       tbb
        "${GLEW_LIBRARIES}"
        "${OPENGL_gl_LIBRARY}"
        "${FREETYPE_LIBRARIES}"
```

To be clear: I believe this PR should be merged even without my changes, it's clearly a step in the right direction for modernizing the available libraries.

**Comment by sesse** [comment]
The packaging from system-build-linux.sh doesn't work too well for me. It's missing some CEF components (everything .pak), and it wants to put others (locales/) in /usr/bin. Media and such are put into /usr/share/doc, where I don't think CasparCG will find them, although I haven't checked. Perhaps packaging decisions are better left to distributions, and the tarball layout should stay the same between build-linux.sh and system-build-linux.sh?

**Comment by dimitry-ishenko** [comment]
@mauricev78 @sesse sorry I am unable to attend to this at the moment, but I will take try to take a look some time next week :unamused:

**Pull request closed without merging**
