### PR TITLE
fix(html) #955 WebM video doesn't play without GPU enabled

### LINKED ISSUE #955: CasperCG wont play WebM embeded HTML pages
Bit of a strage one, if you have a html page with a embeded webM video CasperCG errors with

PLAY 1-1 [HTML] https://webmail.tbdproductions.com.au/disp/test.html
[2018-03-31 21:49:46.928] [info]    Received message from Console: PLAY 1-1 [HTML] https://webmail.tbdproductions.com.au/disp/test.html\r\n
#202 PLAY OK
[0331/214949.917:ERROR:gpu_main.cc(164)] Exiting GPU process due to errors during initialization
[0331/214950.081:ERROR:gpu_main.cc(164)] Exiting GPU process due to errors during initialization
[0331/214950.244:ERROR:gpu_main.cc(164)] Exiting GPU process due to errors during initialization

An example is here
https://webmail.tbdproductions.com.au/disp/test.html

It does work when GPU is enabled, but not when output is a decklink

Kingsley

### PR DESCRIPTION
**Pull request by Julusian**
Fixes #955

@dotarmin The build server scripts will need checking to ensure they copy this folder across too

### CODE REVIEW

**Comment by dotarmin** [comment]
Hey @Julusian!

I can fix this hopefully tomorrow otherwise i'll fix it on Monday morning. 
It's just copy about copying the whole swiftshader folder? :)

**Comment by Julusian** [comment]
> It's just copy about copying the whole swiftshader folder?

Yes, the whole swiftshader folder is needed. It should be being copied with everything else now, so will be really simple to do

**Comment by dotarmin** [comment]
Fixed! swiftshader folder is copied to the root just as locales folder is (from CEF).

**Comment by Pimpmuckl** [comment]
Just built everything on Linux (Ubuntu 18.04) and the swiftshader wasn't created after building everything fresh from master. Manually creating a swiftshader folder and copying the libraries from the lib folder fixed it, but doesn't seem to be entirely fixed quite yet.

**Comment by dotarmin** [comment]
@Pimpmuckl Did you use Docker for building your 18.04 build? If yes, I'm not sure if the docker-images has been updated. 

ping @Julusian

**Comment by Julusian** [comment]
Yep. I forgot to set it to be copied for linux. Fixed in: #985

I checked this building in docker. I shall check without too

**Pull request merged**
