### PR TITLE
return support for SBS key

### PR DESCRIPTION
**Pull request by polardegausser**
Return the support for side-by-side key (for budget builds with dual HDMI output)

### CODE REVIEW

**Comment by ronag** [comment]
@polardegausser: Thanks! Unfortunately this will have to wait until next release. Sorry.

**Comment by ronag** [comment]
@polardegausser could we do this using 2 render calls instead of the memshfl? We are planning to skip the device->host->device round trip in future releases which would break this implementation.

**Comment by Julusian** [comment]
@polardegausser this was closed unintentionally as part of a branch rename. Please open a new pr against the master branch of you want it to be considered for merging :)

**Comment by Andols0** [comment]
Is this abandoned or on hold?

**Pull request closed without merging**
