### PR TITLE
cef 3.3029.1619 / chromium 58.0.3029.81 on windows

### PR DESCRIPTION
**Pull request by AndreasWilladsen**
The implementation works on windows

### CODE REVIEW

**Comment by jesperstarkar** [comment]
@ronag can you have a look at this?

**Comment by Julusian** [comment]
I have found this version to perform much better than the existing version, especially with css transformations.

**Comment by AndreasWilladsen** [comment]
Does anyone want to help me to get webgl working in this version??

**Comment by Julusian** [comment]
Assuming the CEF docs are accurate, it looks as though it won't be possible to get webgl working currently:
``` Off-screen rendering does not currently support accelerated compositing so performance may suffer as compared to a windowed browser.``` (https://bitbucket.org/chromiumembedded/cef/wiki/GeneralUsage#markdown-header-off-screen-rendering)

However this seems to say that it might be possible: https://bitbucket.org/chromiumembedded/cef/issues/1664/linux-2357-webgl-does-not-load

**Comment by AndreasWilladsen** [comment]
@Julusian If I look at [release notes](https://bitbucket.org/chromiumembedded/cef/wiki/ReleaseNotes) for 3.2171.1979, it states that it should work:

> Re-implement off-screen rendering using the new delegated rendering approach (issue #1257). This implementation supports both GPU compositing and software compositing (used when GPU is not supported or when passing --disable-gpu --disable-gpu-compositing command-line flags). GPU-accelerated features (WebGL and 3D CSS) that did not work with the previous off-screen rendering implementation do work with this implementation when GPU support is available.

The cefclient that comes along with CEF also works fine with webgl in offscreen mode. I will try tomorrow with the latest dev build of CEF to see if anything new could help on making it work in CasparCG.

**Comment by deedos** [comment]
Would it be possible to have Linux support as well ?

**Comment by drakmor** [comment]
WebGL worked 
webgl

command line:
casparcg.exe casparcg.config  --enable-gpu-rasterization --gpu-rasterization-msaa-sample-count=16  --enable-gpu  --enable-gpu-compositing --enable-begin-frame-scheduling

[2016-03-12 21:53:27.795] [22316] [info]    cef.version 3.2641.1390
[2016-03-12 21:53:27.797] [22316] [info]    cef.chromeversion 50.0.2641.0

Latest CEF:
https://dl.dropboxusercontent.com/u/3830630/cef/cef_binary_3.2641.1390.g1b8f76d_windows64.zip
https://dl.dropboxusercontent.com/u/3830630/cef/cef_binary_3.2641.1390.g1b8f76d_windows64_debug_symbols.zip
https://dl.dropboxusercontent.com/u/3830630/cef/cef_binary_3.2641.1390.g1b8f76d_windows64_release_symbols.zip

**Comment by jesperstarkar** [comment]
@HellGore?

**Comment by Julusian** [comment]
@drakmor When I try running your test build I get the following error. Any ideas why?

cef-exception

**Comment by AndreasWilladsen** [comment]
Updated to cef 3.2840.1518 / chrome 54.0.2840.99 wihch seems to get webgl to function properly.

**Comment by 5opr4ni** [comment]
Hi, we Will have a look into this. Keep up the good work.

**Comment by dotarmin** [comment]
@AndreasWilladsen Nice work!

**Comment by jesperstarkar** [comment]
Christmas came early this year?

**Comment by Julusian** [comment]
I attempted this myself with 3.2840.1517 about 2 weeks ago, and got awful performance compared to native chrome. It matched up with the OSR example from libcef though so I expect its not caspar at fault.
This looks promising in resolving the issue: https://bitbucket.org/chromiumembedded/cef/issues/2046/improve-gpu-readback-performance-for-osr

I shall still be test this myself in case I did something wrong :)

**Comment by AndreasWilladsen** [comment]
@Julusian A pull request has just been submitted to CEF - https://bitbucket.org/chromiumembedded/cef/pull-requests/96/osr-fix-gpu-cpu-readback-performance/diff

I'm currently building that version and will try it in casparcg once compiled etc.

**Comment by jesperstarkar** [comment]
I _love_ the Open Source nature that gives us such a PR from a company doing commercial CG systems (Ventuz) :)

**Comment by 5opr4ni** [comment]
@Jesperstarkar     ?

**Comment by jesperstarkar** [comment]
@5opr4ni The CEF PR comes from Ventuz.

**Comment by 5opr4ni** [comment]
Ok

**Comment by jesperstarkar** [comment]
Any news on this @AndreasWilladsen ?

**Comment by AndreasWilladsen** [comment]
@jesperstarkar Didn't work that great. FPS is up and that's good, but I couldn't get it to run http://oortonline.gl, any demos on babylonjs.com and some of the examples on threejs.org didn't look correct.

**Comment by jesperstarkar** [comment]
Still you got an updated Chromium with better text rendering, smoothing, CSS Transitions and better performance? If so, that fits my definition of great :)

Looking forward to testing a build.

**Comment by AndreasWilladsen** [comment]
Go nuts. https://www.dropbox.com/s/7tgawxjfbx6bj39/CasparCG%20Server.zip?dl=0

**Comment by jesperstarkar** [comment]
Thank you Sir! Will test and report back.

**Comment by jesperstarkar** [comment]
@AndreasWilladsen It says "chrome_elf.dll" is missing from the system. What do I have to do to get that?

**Comment by AndreasWilladsen** [comment]
Download the file again. It contains the missing file now.

**Comment by jesperstarkar** [comment]
It produces one of these every 5-7ms:

`[2016-12-05 11:05:21.207] [2272] [fatal]   #######################
[2016-12-05 11:05:21.207] [2272] [fatal]    UNHANDLED EXCEPTION: 
[2016-12-05 11:05:21.207] [2272] [fatal]   Adress:000007FEE30B08BD
[2016-12-05 11:05:21.207] [2272] [fatal]   Code:2147483651
[2016-12-05 11:05:21.207] [2272] [fatal]   Flag:0
[2016-12-05 11:05:21.207] [2272] [fatal]   Info:000000000AFADFD0
[2016-12-05 11:05:21.207] [2272] [fatal]   Continuing execution. 
[2016-12-05 11:05:21.207] [2272] [fatal]   #######################
[2016-12-05 11:05:21.213] [2272] [info]    callstack (cef):
[2016-12-05 11:05:21.213] [2272] [info]    
[2016-12-05 11:05:21.213] [2272] [info]        shell\windows_specific.cpp (55): caspar::UserUnhandledExceptionFilter
[2016-12-05 11:05:21.213] [2272] [info]        0000000077A0BC10 (kernel32): (filename not available): UnhandledExceptionFilter
[2016-12-05 11:05:21.213] [2272] [info]        0000000077B10108 (ntdll): (filename not available): EtwEventSetInformation
[2016-12-05 11:05:21.213] [2272] [info]        0000000077AA7958 (ntdll): (filename not available): _C_specific_handler
[2016-12-05 11:05:21.213] [2272] [info]        0000000077AB812D (ntdll): (filename not available): RtlDecodePointer
[2016-12-05 11:05:21.213] [2272] [info]        0000000077AA855F (ntdll): (filename not available): RtlUnwindEx
[2016-12-05 11:05:21.213] [2272] [info]        0000000077ADBCB8 (ntdll): (filename not available): KiUserExceptionDispatcher
[2016-12-05 11:05:21.213] [2272] [info]        000007FEE30B08BD (libcef): (filename not available): GetHandleVerifier
[2016-12-05 11:05:21.213] [2272] [info]        000007FEE30361B7 (libcef): (filename not available): cef_time_to_timet
[2016-12-05 11:05:21.213] [2272] [info]        000007FEE3561EE2 (libcef): (filename not available): GetHandleVerifier
[2016-12-05 11:05:21.213] [2272] [info]        000007FEE2F6F268 (libcef): (filename not available): cef_zip_reader_create
[2016-12-05 11:05:21.213] [2272] [info]        000007FEE2F82B2B (libcef): (filename not available): cef_string_list_value
[2016-12-05 11:05:21.213] [2272] [info]        000007FEE2F82621 (libcef): (filename not available): cef_string_list_value
[2016-12-05 11:05:21.213] [2272] [info]        000007FEE1EC0518 (libcef): (filename not available): cef_initialize
[2016-12-05 11:05:21.213] [2272] [info]        c:\src\cef_binary_3.2924.1535.g262a7df_windows64\libcef_dll\wrapper\libcef_dll_wrapper.cc (208): CefInitialize
[2016-12-05 11:05:21.213] [2272] [info]        modules\html\html.cpp (249): <lambda_731d7855a1eac41cb179900f3a13e92d>::operator()
[2016-12-05 11:05:21.213] [2272] [info]        functional (212): std::_Func_impl<<lambda_493e3d24ce1354bbb728ef0518256faa>,std::allocator<int>,void>::_Do_call
[2016-12-05 11:05:21.213] [2272] [info]        future (749): std::_Packaged_state<void __cdecl(void)>::_Call_immediate
[2016-12-05 11:05:21.213] [2272] [info]        common\executor.h (234): <lambda_a27145077a5a0f312bcfe29c35cbb31f>::operator()
[2016-12-05 11:05:21.213] [2272] [info]        common\executor.h (286): caspar::executor::run
[2016-12-05 11:05:21.213] [2272] [info]        000000013F9744A3 (casparcg): (filename not available): boost::detail::shared_count::swap
[2016-12-05 11:05:21.213] [2272] [info]        000007FEF73BBE1D (ucrtbase): (filename not available): crt_at_quick_exit
[2016-12-05 11:05:21.213] [2272] [info]        00000000779859CD (kernel32): (filename not available): BaseThreadInitThunk
[2016-12-05 11:05:21.213] [2272] [info]        0000000077ABA561 (ntdll): (filename not available): RtlUserThreadStart`

**Comment by drakmor** [comment]
Some error:

> [2016-12-05 17:15:19.637] [15012] [info]    Initialized screen module.
> [2016-12-05 17:15:19.640] [9684]  [fatal]   #######################
> [2016-12-05 17:15:19.640] [9684]  [fatal]    UNHANDLED EXCEPTION: 
> [2016-12-05 17:15:19.640] [9684]  [fatal]   Adress:00007FFCAF1608BD
> [2016-12-05 17:15:19.640] [9684]  [fatal]   Code:2147483651
> [2016-12-05 17:15:19.640] [9684]  [fatal]   Flag:0
> [2016-12-05 17:15:19.640] [9684]  [fatal]   Info:000000DD26AFDED0
> [2016-12-05 17:15:19.640] [9684]  [fatal]   Continuing execution. 
> [2016-12-05 17:15:19.640] [9684]  [fatal]   #######################
> [2016-12-05 17:15:19.667] [9684]  [info]    callstack (cef):
> [2016-12-05 17:15:19.667] [9684]  [info]    
> [2016-12-05 17:15:19.667] [9684]  [info]        shell\windows_specific.cpp (55): caspar::UserUnhandledExceptionFilter
> [2016-12-05 17:15:19.667] [9684]  [info]        00007FFCF9638EC7 (KERNELBASE): (filename not available): UnhandledExceptionFilter
> [2016-12-05 17:15:19.667] [9684]  [info]        00007FFCFC50CBDB (ntdll): (filename not available): memset
> [2016-12-05 17:15:19.667] [9684]  [info]        00007FFCFC4F541F (ntdll): (filename not available): _C_specific_handler
> [2016-12-05 17:15:19.667] [9684]  [info]        00007FFCFC509B1D (ntdll): (filename not available): _chkstk
> [2016-12-05 17:15:19.667] [9684]  [info]        00007FFCFC493AE1 (ntdll): (filename not available): RtlImageNtHeaderEx
> [2016-12-05 17:15:19.667] [9684]  [info]        00007FFCFC508BFA (ntdll): (filename not available): KiUserExceptionDispatcher
> [2016-12-05 17:15:19.667] [9684]  [info]        00007FFCAF1608BD (libcef): (filename not available): GetHandleVerifier
> [2016-12-05 17:15:19.667] [9684]  [info]        00007FFCAF0E61B7 (libcef): (filename not available): cef_time_to_timet
> [2016-12-05 17:15:19.667] [9684]  [info]        00007FFCAF611EE2 (libcef): (filename not available): GetHandleVerifier
> [2016-12-05 17:15:19.667] [9684]  [info]        00007FFCAF01F268 (libcef): (filename not available): cef_zip_reader_create
> [2016-12-05 17:15:19.667] [9684]  [info]        00007FFCAF032B2B (libcef): (filename not available): cef_string_list_value
> [2016-12-05 17:15:19.667] [9684]  [info]        00007FFCAF032621 (libcef): (filename not available): cef_string_list_value
> [2016-12-05 17:15:19.667] [9684]  [info]        00007FFCADF70518 (libcef): (filename not available): cef_initialize
> [2016-12-05 17:15:19.667] [9684]  [info]        c:\src\cef_binary_3.2924.1535.g262a7df_windows64\libcef_dll\wrapper\libcef_dll_wrapper.cc (208): CefInitialize
> [2016-12-05 17:15:19.667] [9684]  [info]        modules\html\html.cpp (249): <lambda_731d7855a1eac41cb179900f3a13e92d>::operator()
> [2016-12-05 17:15:19.667] [9684]  [info]        functional (212): std::_Func_impl<<lambda_493e3d24ce1354bbb728ef0518256faa>,std::allocator<int>,void>::_Do_call
> [2016-12-05 17:15:19.667] [9684]  [info]        future (749): std::_Packaged_state<void __cdecl(void)>::_Call_immediate
> [2016-12-05 17:15:19.667] [9684]  [info]        common\executor.h (234): <lambda_a27145077a5a0f312bcfe29c35cbb31f>::operator()
> [2016-12-05 17:15:19.667] [9684]  [info]        common\executor.h (286): caspar::executor::run
> [2016-12-05 17:15:19.667] [9684]  [info]        00007FF77C0B44A3 (casparcg): (filename not available): boost::detail::shared_count::swap
> [2016-12-05 17:15:19.667] [9684]  [info]        00007FFCF9123F22 (ucrtbase): (filename not available): o_isupper
> [2016-12-05 17:15:19.667] [9684]  [info]        00007FFCFB2D38E4 (KERNEL32): (filename not available): BaseThreadInitThunk
> [2016-12-05 17:15:19.667] [9684]  [info]        00007FFCFC4B1561 (ntdll): (filename not available): RtlUserThreadStart
>

**Comment by AndreasWilladsen** [comment]
Give this one a shot instead: https://www.dropbox.com/s/nfh4e0u73gt392e/casparcg_custom_cef.zip?dl=0

**Comment by drakmor** [comment]
No working images and css-backgound (

**Comment by drakmor** [comment]
Does anyone else have a problem with images?

**Comment by jesperstarkar** [comment]
I was going to test this properly now, just downloaded from the last link again, and got this error:
> OpenAL32.dll missing

**Comment by drakmor** [comment]
Latest CEF 3.2924.1537 binaries (not patched)  - https://drive.google.com/drive/folders/0B4i_lamQ3ck5MTZuODNPd01NOTA?usp=sharing

**Comment by drakmor** [comment]
Latest CEF + OSR Patch (https://bitbucket.org/chromiumembedded/cef/pull-requests/96/osr-fix-gpu-cpu-readback-performance/diff)

https://drive.google.com/file/d/0B4i_lamQ3ck5d0tWVm9RXzRiY0k/view?usp=sharing

casparcg.exe casparcg.config --show-fps-counter
casparcg.exe casparcg.config --enable-gpu -off-screen-frame-rate=60 --enable-begin-frame-scheduling --show-fps-counter

Please test.

**Comment by snakemastr** [comment]
Is it possible to update the Linux CEF dep also?

**Comment by jesperstarkar** [comment]
@drakmor I have been testing your build with and without the given flags.
What demo do you run, and what FPS do you get with CasparCG?

**Comment by henriklied** [comment]
Looks promising so far! I was able to run the Three.JS Flocking example (https://nrkbeta.no/saus/flock.html#90) with 8100 birds at 50fps without any issues aside from huge memory usage (it ran through my 16GB in a minute or so). But this might just be a memory leak in the flocking example.

**Comment by HellGore** [comment]
I have started to look at this now and I can't get good framerate at all with https://nrkbeta.no/saus/flock.html#90.

https://www.dropbox.com/s/nfh4e0u73gt392e/casparcg_custom_cef.zip?dl=0
with that version it reads 50fps according to the browser, but it is very laggy in caspar so I don't think the frames are delivered in time to caspar.

https://drive.google.com/file/d/0B4i_lamQ3ck5d0tWVm9RXzRiY0k/view?usp=sharing
seems to have a CEF version compiled against visual studio 2010 runtime instead of 2015.

**Comment by jesperstarkar** [comment]
I actually have much better results on the main branch of 2.1 than these builds. In master, #64 works perfect, but any resolution above this cuts the birds in half, leaving them with a single wing.

**Comment by HellGore** [comment]
You are right `#60` works without problem on my computer on the old CEF with in 1080i50.

`#90` works in 720p50

**Comment by henriklied** [comment]
Seems to be some memory exhaustion in this build. Tried running a [CSS3 snow demo](http://codepen.io/NickyCDK/full/AIonk), and it failed with this error message after about five minutes: 

image

The results while it was actually running weren't that great either. A lot more laggy than on my laptop.

**Comment by henriklied** [comment]
Could it be related to [this](https://bitbucket.org/chromiumembedded/cef/issues/1855/)?

**Comment by pkeuter** [comment]
@AndreasWilladsen Your latest commit doesn't seem to compile anymore. There are a bunch of unresolved externals. I tried some of the latest Spotify-builds, but they all give the same errors. Were you able to compile be448ce successfully? And if so, what did you change?

**Comment by pkeuter** [comment]
@AndreasWilladsen Thanks, that helps. Would you mind telling what you did? Since it's a binary file it is hard to figure out what you've changed. Also, I would like to be able to create a debug build, which is not possible now because you only committed the release version. Thanks again!

**Comment by AndreasWilladsen** [comment]
@pkeuter yes exactly the libcef_dll_wrapper has to be MD. I forgot that on the commit that failed.

**Comment by Punkley** [comment]
Is there any chance of getting a new compile up?

**Comment by Julusian** [comment]
@Punkley https://drive.google.com/open?id=0B4xCe4AF2PEUREZjTVk3SkQtdm8

**Comment by Julusian** [comment]
Try redownloading. I had to replace a few of the cef assets for it to run so it was easier to reupload the zip.

**Comment by Punkley** [comment]
Thank you it is working, 

next question, one thing I have noticed, if you are loading a remote page (from a slower site), it appears you get a white flash before the page starts loading. Like it is defaulting to a white background before the transparancy loads. Has anyone else seen this?

**Comment by ronag** [comment]
Closing in favor of https://github.com/CasparCG/Server/pull/611

**Pull request closed without merging**
