### PR TITLE
Windows cmake to /build directory & cef include nuget

### PR DESCRIPTION
**Pull request by Julusian**
This currently gives me an error building the image module, I havent looked into why. Thought it best to share what I have in case someone wants to look into it as I wont have time until next week.

This also moved the cef includes into nuget. Might be cherry-pickable, but it also might rely on the previous commit to work properly

### CODE REVIEW

**Comment by Julusian** [comment]
@ronag I am happy with this now, after your image producer fix it is building for me.
The only bit I am uncertain about is that if a new nuget package gets added, the matching files in /src will likely need manual updating, but that wont happen often so I think it is fine.

The build docs have been updated to reflect this.

Fixes #766

**Comment by ronag** [comment]
@k0d please take a look

**Comment by ronag** [comment]
@Julusian could you resolve last conflicts and then I'll merge. Thanks!

**Comment by ronag** [comment]
Does version.h work with this?

**Comment by Julusian** [comment]
Sure, ill rebase this when I have some time later today.

I'm not sure if version.h works, but I shall check

**Comment by Julusian** [comment]
@ronag This is rebased on latest 2.2.0

**Comment by ronag** [comment]
@Julusian where should the sln file end up?

**Comment by Julusian** [comment]
It will end up in whatever folder cmake is run from. The build docs have been updated to say to run it from within a /build folder, but it should also work as before when cmake is run in /src

**Comment by ronag** [comment]
@Julusian I seem to have some problems with release build

**Comment by ronag** [comment]
```

15>libcef_dll_wrapper.lib(navigation_entry_ctocpp.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in main.obj
15>libcef_dll_wrapper.lib(navigation_entry_ctocpp.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MD_DynamicRelease' in main.obj
```

**Comment by ronag** [comment]
@Julusian probably something to do with the cef changes.

**Comment by Julusian** [comment]
strange, I thought I checked that... Ill have a look now

**Pull request merged**
