### PR TITLE
Adds support to CasparCG 2.1.x for 2160p5000, 2160p5994 and 2160p6000 video modes

### PR DESCRIPTION
**Pull request by aruanoc**
This pull request adds support to CasparCG 2.1..x for 2160p5000, 2160p5994 and 2160p6000 video modes.

### CODE REVIEW

**Comment by HellGore** [comment]
Is your full name Antonio Ruano Cuesta?

**Comment by aruanoc** [comment]
Yes, it is

**Comment by HellGore** [comment]
Could you also make a pull request against https://github.com/CasparCG/Framework/tree/master/as3/TemplateHost/trunk with the source code of the template hosts?

**Comment by aruanoc** [comment]
Done

**Comment by HellGore** [comment]
@jeansson will review your changes to the template host

**Pull request merged**
