### PR TITLE
Support for playing rtmp video streams

### PR DESCRIPTION
**Pull request by Julusian**
This adds support for playing video streams (rtmp/http/udp etc) through ffmpeg.

Inspired by #131 

Note: Only works for streams with 48K audio, as normal video playback was failing when resampling is required (#451)

### CODE REVIEW

**Comment by baltedewit** [comment]
Compiling on Linux succeeds but trying to play back the following stream just gives me errrors: rtmp://vps48678.ovh.net/live/

't was running fine on 2.0.7

**Comment by Julusian** [comment]
Hi @baltedewit, you appear to have missed off the end of the stream url so I cannot verify this, but I assume that the stream has 44.1K audio. 
If so then I believe that #451 is a relevent issue to you, which got me confused for a few hours when coding this.

**Comment by baltedewit** [comment]
The right livestream is rtmp://vps48678.ovh.net/live/livestream

Sorry about that. I said nothing.

**Comment by Julusian** [comment]
Thanks, I can see that it is not the issue I thought, but looks like some missing frame/packet in the stream. Ill see what I can do to make it be handled better.

**Comment by HellGore** [comment]
This now works since the port from 2.0.7 that I just did.

**Pull request closed without merging**
