### PR TITLE
Win8 Support + HTML Cross Domain

### PR DESCRIPTION
**Pull request by ronag**

### CODE REVIEW

**Comment by tomswinkels** [comment]
Could this be merged into the master? We're still exp. problems with the Cross Domain lock.

**Comment by tomswinkels** [comment]
Any update?

**Comment by coral** [comment]
@tomswinkels It's vacation in Sweden so i guess they might be off.

**Comment by tomswinkels** [comment]
@coral Thanks, I hope that soon an update is coming!

**Comment by tomswinkels** [comment]
Is there any update? Fix this us issue? https://github.com/CasparCG/Server/issues/311

**Comment by ronag** [comment]
This was cherry-picked into 2.1

**Pull request closed without merging**
