### PR TITLE
Adds support to CasparCG 2.0.7.x for 2160p5000, 2160p5994 and 2160p6000 video modes

### PR DESCRIPTION
**Pull request by aruanoc**
This pull request adds support to CasparCG 2.0.7.x for 2160p5000, 2160p5994 and 2160p6000 video modes.

### CODE REVIEW

**Comment by HellGore** [comment]
Sorry but the changes should be against the 2.1.0 branch.

**Comment by HellGore** [comment]
Sorry again didn't see that you already made that

**Comment by aruanoc** [comment]
I added the new video modes to master and 2.1.0 separately because I think they have diverged so much that you can't cleanly merge 2.1.0 back into master anymore, correct? Also, the decklink SDK version in master is older and I had to add support to the new video modes myself (the 2.1.0 SDK already accounts for them).

**Comment by HellGore** [comment]
That is correct.

**Comment by aruanoc** [comment]
Did you already freeze master (i.e. don't merge any new code)? Despite 2.1.0 being the future, I think it's still worth to have high frame rate 4K support in 2.0.7.x (this is actually what we've been using in production for a while).

**Pull request merged**
