### PR TITLE
Frame-accurate seeking files with long-GOP

### PR DESCRIPTION
**Pull request by jaskie**
Ensures correct seeking and A/V synchronization using packet's PTS values. It decodes all frames of video from keyframe (where file position is after avformat_seek_file) and discard if they are before requested frame number. This, of course, requires additional processing time. All calculations are in FFmpeg's AV_TIME_BASE units.

### CODE REVIEW

**Comment by maceyldn** [comment]
@HellGore , Any reason we can't merge?

**Comment by jaskie** [comment]
This particular patch should be reviewed to work under 2.07. I recommend suspension - I’ll do it next month, I expect.

**Comment by TomKaltz** [comment]
All work is current being done on the 2.1.0 branch.  Any chance you can take a stab at porting this PR to that branch?

@HellGore I am not quite sure about the ffmpeg producer in 2.1.0.  Would a PR like this against the 2.1.0 branch be useful?

**Comment by jesperstarkar** [comment]
@ronag @5opr4ni Is this something that should be considered for the 2.1 sprint?

**Comment by ronag** [comment]
@jesperstarkar: It will be fixed in the re-write.

**Pull request closed without merging**
