### PR TITLE
Disable html module when CEF is unavailable.

### PR DESCRIPTION
**Pull request by petterreinholdtsen**
Add FindCEF cmake rule to detect when CEF is available.

### CODE REVIEW

**Comment by Julusian** [comment]
It would be better to require the user to explicitly state they do not want to include CEF as a build option. Otherwise it risks producing an 'incomplete' build if CEF wasn't found but should have been (eg typo in path name)

**Comment by petterreinholdtsen** [comment]
While I would be happy to make such change, I do not know cmake well enough to know how to do it.  Any clues to spare?

**Comment by petterreinholdtsen** [comment]
I rewrote the rules to make enabling the HTML module a cmake option.  It is enabled by default.  I hope it addresses your concerns. :)

**Comment by petterreinholdtsen** [comment]
It would be great if this change was included in the next release.  Is there any hope to have it included?

**Pull request merged**
