### PR TITLE
Remove boost::noncopyable pattern

### PR DESCRIPTION
**Pull request by drakmor**

### CODE REVIEW

**Comment by drakmor** [comment]
`void operator=(const A&) = delete; ` instead of  ` void operator=(const A&) = delete` for prevent `A=B=C;` construction

**Comment by drakmor** [comment]
@ronag return classic `const A& operator=(const A&)` ? Or leave boost :: noncopyable?

**Comment by ronag** [comment]
I don’t get the void return. What’s that about? I don’t see the point when you are deleting the operator.

**Comment by drakmor** [comment]
Updated. Removed "void".

**Comment by ronag** [comment]
LGTM

**Pull request merged**
