### PR TITLE
fix(decklink_consumer): frame scheduling

### PR DESCRIPTION
**Pull request by ronag**

### CODE REVIEW

**Comment by ronag** [comment]
@dotarmin Can you please try and put back the 2000 card in a machine and try to reproduce the issue with current master, and then try it with this PR and see if there is any difference.

**Comment by dotarmin** [comment]
Yes I can do that tomorrow @ronag 👊

**Comment by Julusian** [comment]
From a glance this looks to revert https://github.com/CasparCG/server/pull/1255 so this will reintroduce timing issues for interlaced channels instead

**Comment by ronag** [comment]
> From a glance this looks to revert #1255 

Yep. I'm sorry I missed that PR.

> reintroduce timing issues for interlaced channels instead

What exactly was the issues?

**Comment by Julusian** [comment]
> What exactly was the issues? "which has an impact on the processing occurring upstream." is a bit vague.

The original issue: https://github.com/CasparCG/server/issues/1165

Additionally I think the route producer was affected too, as it was trying to maintain a tiny frame buffer, which meant requesting 2 frames in short succession would often result in the buffer running out.

**Comment by ronag** [comment]
I don't like the current solution but I don't have a better suggestion at the moment.

**Pull request closed without merging**
