### PR TITLE
Fix compilation in VS2015 version 14.0.24720.00 Update 1

### PR DESCRIPTION
**Pull request by drakmor**
Fixed issue #410

### CODE REVIEW

**Comment by HellGore** [comment]
According to this: http://stackoverflow.com/questions/34013930/error-c4592-symbol-will-be-dynamically-initialized-vs2015-1-static-const-std this is a bug which Microsoft has fixed, and the fix will be available in the next update.

**Comment by HellGore** [comment]
If you disable the warning in `common/compiler/vs/disable_silly_warnings.h` instead I will merge this

**Comment by elanvrt** [comment]
Ah, that disable_silly_warnings.h was the place I didn't know about...

**Comment by drakmor** [comment]
move fix to disable_silly_warnings.h

**Pull request merged**
