### PR TITLE
Enable CPU Mixer for linux

### PR DESCRIPTION
**Pull request by Julusian**
Enables the cpu mixer for linux.

It appears it was originally disabled due to the differing ```__m128i``` type definition in GCC vs VS.
Its not the prettiest fix, but it works.

http://casparcg.com/forum/viewtopic.php?f=3&t=4651

### CODE REVIEW

**Comment by sesse** [comment]
@Julusian: I tried your patch, and it appears to work well. However, it uses a lot of CPU; much more than I'd expect. I applied the (fairly trivial) patch below to help GCC a bit on its way, which speeds it up 5x or so. (At this point, it's using less CPU for me than the GPU mixer does, although I haven't kept up with the latest GPU mixer changes in mainline.)

```diff
diff --git a/accelerator/cpu/image/image_mixer.cpp b/accelerator/cpu/image/image_mixer.cpp
index 45160c4ab..404df00bf 100644
--- a/accelerator/cpu/image/image_mixer.cpp
+++ b/accelerator/cpu/image/image_mixer.cpp
@@ -160,20 +160,21 @@ public:
 
 		convert(items, format_desc.width, format_desc.height);
 
-		auto result = spl::make_shared<buffer>(format_desc.size, 0);
+		auto result = std::shared_ptr<uint8_t[]>(new uint8_t[format_desc.size]);
+		memset(result.get(), 0, format_desc.size);
 		if(format_desc.field_mode != core::field_mode::progressive)
 		{
-			draw(items, result->data(), format_desc.width, format_desc.height, core::field_mode::upper);
-			draw(items, result->data(), format_desc.width, format_desc.height, core::field_mode::lower);
+			draw(items, result.get(), format_desc.width, format_desc.height, core::field_mode::upper);
+			draw(items, result.get(), format_desc.width, format_desc.height, core::field_mode::lower);
 		}
 		else
 		{
-			draw(items, result->data(), format_desc.width, format_desc.height,  core::field_mode::progressive);
+			draw(items, result.get(), format_desc.width, format_desc.height,  core::field_mode::progressive);
 		}
 
 		temp_buffers_.clear();
 
-		return make_ready_future(array<const std::uint8_t>(result->data(), format_desc.size, true, result));
+		return make_ready_future(array<const std::uint8_t>(result.get(), format_desc.size, true, result));
 	}
 
 private:
diff --git a/accelerator/cpu/util/xmm.h b/accelerator/cpu/util/xmm.h
index e6dd24172..e52025f11 100644
--- a/accelerator/cpu/util/xmm.h
+++ b/accelerator/cpu/util/xmm.h
@@ -89,34 +89,34 @@ private:
 public:
 	typedef s16_x xmm_epi_tag;
 
-	s16_x();
-	explicit s16_x(const s32_x& other);
-	explicit s16_x(const s8_x& other);
-	explicit s16_x(const u8_x& other);
-	s16_x(const __m128i& value);
-	s16_x(short value);
-
-	s16_x& operator+=(const s16_x& other);	
-	s16_x& operator-=(const s16_x& other);
-	s16_x& operator>>=(int count);
-	s16_x& operator<<=(int count);
-	s16_x& operator|=(const s16_x& other);
-	s16_x& operator&=(const s16_x& other);	
-	int16_t operator[](int index) const;
-	int16_t& operator[](int index);
+	inline s16_x();
+	explicit inline s16_x(const s32_x& other);
+	explicit inline s16_x(const s8_x& other);
+	explicit inline s16_x(const u8_x& other);
+	inline s16_x(const __m128i& value);
+	inline s16_x(short value);
+
+	inline s16_x& operator+=(const s16_x& other);	
+	inline s16_x& operator-=(const s16_x& other);
+	inline s16_x& operator>>=(int count);
+	inline s16_x& operator<<=(int count);
+	inline s16_x& operator|=(const s16_x& other);
+	inline s16_x& operator&=(const s16_x& other);	
+	inline int16_t operator[](int index) const;
+	inline int16_t& operator[](int index);
 	
-	static s16_x unpack_low(const s8_x& lhs, const s8_x& rhs);
-	static s16_x unpack_high(const s8_x& lhs, const s8_x& rhs);
-	static s32_x horizontal_add(const s16_x& lhs);
-	static s16_x multiply_low(const s16_x& lhs, const s16_x& rhs);
-	static s16_x multiply_high(const s16_x& lhs, const s16_x& rhs);
-	static s16_x umultiply_low(const s16_x& lhs, const s16_x& rhs);
-	static s16_x umultiply_high(const s16_x& lhs, const s16_x& rhs);	
-	static s16_x unpack_low(const s16_x& lhs, const s16_x& rhs);
-	static s16_x unpack_high(const s16_x& lhs, const s16_x& rhs);
-	static s16_x and_not(const s16_x& lhs, const s16_x& rhs);	
-	static s16_x max(const s16_x& lhs, const s16_x& rhs);
-	static s16_x min(const s16_x& lhs, const s16_x& rhs);
+	static inline s16_x unpack_low(const s8_x& lhs, const s8_x& rhs);
+	static inline s16_x unpack_high(const s8_x& lhs, const s8_x& rhs);
+	static inline s32_x horizontal_add(const s16_x& lhs);
+	static inline s16_x multiply_low(const s16_x& lhs, const s16_x& rhs);
+	static inline s16_x multiply_high(const s16_x& lhs, const s16_x& rhs);
+	static inline s16_x umultiply_low(const s16_x& lhs, const s16_x& rhs);
+	static inline s16_x umultiply_high(const s16_x& lhs, const s16_x& rhs);	
+	static inline s16_x unpack_low(const s16_x& lhs, const s16_x& rhs);
+	static inline s16_x unpack_high(const s16_x& lhs, const s16_x& rhs);
+	static inline s16_x and_not(const s16_x& lhs, const s16_x& rhs);	
+	static inline s16_x max(const s16_x& lhs, const s16_x& rhs);
+	static inline s16_x min(const s16_x& lhs, const s16_x& rhs);
 };
 
 template<typename T>
@@ -141,31 +141,31 @@ private:
 public:
 	typedef s8_x xmm_epi_tag;
 
-	s8_x();
-	explicit s8_x(const s32_x& other);
-	explicit s8_x(const s16_x& other);
-	explicit s8_x(const u8_x& other);
-	s8_x(const __m128i& value);	
-	s8_x(char b);
-	s8_x(char b3,  char b2,  char b1,  char b0);
-	s8_x(char b15, char b14, char b13, char b12, 
-		 char b11, char b10, char b9,  char b8,  
+	inline s8_x();
+	inline explicit s8_x(const s32_x& other);
+	inline explicit s8_x(const s16_x& other);
+	inline explicit s8_x(const u8_x& other);
+	inline s8_x(const __m128i& value);	
+	inline s8_x(char b);
+	inline s8_x(char b3,  char b2,  char b1,  char b0);
+	inline s8_x(char b15, char b14, char b13, char b12, 
+	         char b11, char b10, char b9,  char b8,  
 		 char b7,  char b6,  char b5,  char b4,  
 		 char b3,  char b2,  char b1,  char b0);
 
-	s8_x& operator+=(const s8_x& other);
-	s8_x& operator-=(const s8_x& other);	
-	char operator[](int index) const;
-	char& operator[](int index);
+	inline s8_x& operator+=(const s8_x& other);
+	inline s8_x& operator-=(const s8_x& other);	
+	inline char operator[](int index) const;
+	inline char& operator[](int index);
 	
-	static s8_x upack(const s16_x& lhs, const s16_x& rhs);
+	static inline s8_x upack(const s16_x& lhs, const s16_x& rhs);
 
-	static s16_x multiply_add(const u8_x& lhs, const s8_x& rhs);
-	static s8_x max(const s8_x& lhs, const s8_x& rhs);
-	static s8_x min(const s8_x& lhs, const s8_x& rhs);
+	static inline s16_x multiply_add(const u8_x& lhs, const s8_x& rhs);
+	static inline s8_x max(const s8_x& lhs, const s8_x& rhs);
+	static inline s8_x min(const s8_x& lhs, const s8_x& rhs);
 
-	static s8_x shuffle(const s8_x& lhs, const s8_x& rhs);
-	static s8_x blend(const s8_x& lhs, const s8_x& rhs, const s8_x& mask);
+	static inline s8_x shuffle(const s8_x& lhs, const s8_x& rhs);
+	static inline s8_x blend(const s8_x& lhs, const s8_x& rhs, const s8_x& mask);
 };
 
 class u8_x : public base_x<u8_x>
@@ -183,26 +183,26 @@ private:
 public:
 	typedef u8_x xmm_epu_tag;
 
-	u8_x();
-	explicit u8_x(const s32_x& other);
-	explicit u8_x(const s16_x& other);
-	explicit u8_x(const s8_x& other);
-	u8_x(const __m128i& value);	
-	u8_x(char b);
-	u8_x(char b3,  char b2,  char b1,  char b0);
-	u8_x(char b15, char b14, char b13, char b12, 
+	inline u8_x();
+	explicit inline u8_x(const s32_x& other);
+	explicit inline u8_x(const s16_x& other);
+	explicit inline u8_x(const s8_x& other);
+	inline u8_x(const __m128i& value);	
+	inline u8_x(char b);
+	inline u8_x(char b3,  char b2,  char b1,  char b0);
+	inline u8_x(char b15, char b14, char b13, char b12, 
 		 char b11, char b10, char b9,  char b8,  
 		 char b7,  char b6,  char b5,  char b4,  
 		 char b3,  char b2,  char b1,  char b0);
 										
-	char operator[](int index) const;
-	char& operator[](int index);
+	inline char operator[](int index) const;
+	inline char& operator[](int index);
 			
-	static u8_x max(const u8_x& lhs, const u8_x& rhs);
-	static u8_x min(const u8_x& lhs, const u8_x& rhs);
+	static inline u8_x max(const u8_x& lhs, const u8_x& rhs);
+	static inline u8_x min(const u8_x& lhs, const u8_x& rhs);
 		
-	static u8_x shuffle(const u8_x& lhs, const u8_x& rhs);
-	static u8_x blend(const u8_x& lhs, const u8_x& rhs, const u8_x& mask);
+	static inline u8_x shuffle(const u8_x& lhs, const u8_x& rhs);
+	static inline u8_x blend(const u8_x& lhs, const u8_x& rhs, const u8_x& mask);
 };
 
 // base_x
```

**Comment by ronag** [comment]
@sesse would u mind opening a pr for that?

**Comment by sesse** [comment]
On top of Julusian's PR? Or something else?

**Comment by ronag** [comment]
on top of this one

**Comment by sesse** [comment]
OK, I can try cherry-picking this one on top of 2.2.0? I guess that's the right branch?

**Comment by sesse** [comment]
PR #685

**Comment by Julusian** [comment]
Wow. Thats an impressive improvement for what looks like such a simple change.
I haven't used the cpu mixer after writing this PR as a lot of the mixer operations aren't implemented, but its good that it is getting some attention

**Comment by sesse** [comment]
For my part, I don't really care about features—I just have a single untransformed CEF layer anyway. So using the CPU mixer makes a lot of sense there, as “mixing” effectively becomes a no-op.

**Pull request closed without merging**
