### PR TITLE
Add straight-alpha-output info to channel

### PR DESCRIPTION
**Pull request by jlemanbeto**
Hi,

I've needed to know when a channel is straight-alpha or not. So I've add this info in the channel info.

So I can apply the right value on the AMCP command
MIXER 1 STRAIGHT_ALPHA_OUTPUT 1
and get the info with
INFO SERVER
201 INFO SERVER OK
&lt;?xml&nbsp;version="1.0"&nbsp;encoding="utf-8"?&gt;
&lt;channels&gt;
&nbsp;&nbsp;&nbsp;&lt;channel&gt;
...
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;straight-alpha-output&gt;true&lt;/straight-alpha-output&gt;

Hope it'll help someone.
Perhaps, I've not choose the better way to do that.

I'll be very happy to get your point of vue on that.

Thanks in advance.

Jean

### CODE REVIEW

**Comment by jlemanbeto** [comment]
Hi,
Any advice on this pull request?

Thanks in advance.

Regards,

Jean

**Comment by jlemanbeto** [comment]
Just add a commit that fixes an issue.

**Comment by jesperstarkar** [comment]
"MIXER 1 STRAIGHT_ALPHA_OUTPUT" without a value query the current state and returns it. All MIXER commands work this way.

**Comment by jlemanbeto** [comment]
Thanks!!!
That's help a lot.

Best regards

**Comment by jesperstarkar** [comment]
Then this PR can be closed? @HellGore.

**Comment by jlemanbeto** [comment]
Sorry for the pull request that contains two things.
Have you had a look on the "Fix Issue #407" part of the pull request?

Thanks in advance.

Jean

**Comment by jlemanbeto** [comment]
Since I'm not a boost expert, I'm not sure that I've used the right way to fix this path issue.

**Pull request closed without merging**
