### PR TITLE
Code Cleaning, Processing with Clang-Tidy.

### PR DESCRIPTION
**Pull request by drakmor**

### CODE REVIEW

**Comment by drakmor** [comment]
Done

**Comment by Julusian** [comment]
What command did you use to run clang-tidy?
I have just found that building with clang is now outputting a bunch of warnings that appear to be introduced by this change

**Comment by drakmor** [comment]
I use code cleaning through ReShaper. There is processing through clang-tidy.

**Comment by Julusian** [comment]
Thanks, looks like I need to figure out a shell script for it myself at some point then :)

**Pull request merged**
