### PR TITLE
Fix decklink synchronization clock for interlace field mode

### PR DESCRIPTION
**Pull request by ducthiem90**
I found a problem in casparcg version 2.2 when use decklink consumer for synchronization clock in interlace field mode

And I propose a solution to fix it

### CODE REVIEW

**Comment by martastain** [comment]
Any news regarding this? I am eager to test the fix.

**Comment by sirfnomi** [comment]
I'm also waiting for this fix

**Comment by ducthiem90** [comment]
> Any news regarding this? I am eager to test the fix.

Because Casparcg version 2.2 render interlaced field mode as progressive mode with double rate. Ex: 1080i50 rendered with 50fps, but decklink device locked 25fps. So, 2 field are take consecutively but don't have sleep time, it's wrong. I added a sleep time between 2 field (1/2 fps. Ex: 1080i50 will sleep 20ms)

**Comment by Julusian** [comment]
Thanks for looking at this, this is something I noticed a while ago in 2.2, but haven't figured out the right solution yet.
I'm not sure about this solution, as when Caspar falls behind the decklink (eg from high system load), the decklink forces caspar to run as fast as possible to catch up, and this will end up limiting the speed of that happening. But I haven't had any better ideas, so maybe this will be a good first step.

**Comment by Julusian** [comment]
https://github.com/CasparCG/server/pull/1255 has been merged as an improved version of this

**Pull request closed without merging**
