### PR TITLE
Revert "Crossdomain calls in 2.0"

### PR DESCRIPTION
**Pull request by ronag**
Reverts CasparCG/Server#376

Needs to be managed and tested by core team.

### CODE REVIEW

**Comment by maceyldn** [comment]
Sorry bud! Thought you asked me to do it at IBC.

**Comment by ronag** [comment]
There is a difference between doing a pull request and merging it. You shouldn't really have had access to do the merge so don't worry about it.

**Comment by maceyldn** [comment]
Wheres the *like* button ;)

**Comment by Zebiolo** [comment]
No one need to apologise.

The change is already in the 2.1 branch. If we never stop adding stuff to 2.0, we will never get the 2.1 out of the door.

**Pull request merged**
