### PR TITLE
Pbus

### PR DESCRIPTION
**Pull request by ronag**
Not entirely clean PR. Needs some love. But the basics are there.

### CODE REVIEW

**Comment by TomKaltz** [comment]
@ronag Can you explain a little how PBUS feature works?  From reading the code it seems it triggers macros from a new special directory?

**Comment by ronag** [comment]
Yes, you create regular text files in a "macro" directory. PBUS commands will cause the server to read in the text file and execute all the commands, There is also a special token "#WAIT" that will pause the execution of the macro.

**Comment by TomKaltz** [comment]
file naming convention/mapping from PBUS register to macro?

**Comment by yapus** [comment]
related to enhancement #171.
But i suggest that we not make PBUS one and only serial protocol available. Would be great if you add controllers.serial.protocol = "PBUS" configuration setting to choose PBUS protocol so other people can extend <serial> controller with other protocols

**Comment by dimitry-ishenko** [comment]
In case anyone is interested, I am in the process of writing a simple PBus -> AMCP translator app:

https://github.com/dimitry-ishenko-casparcg/pbus2amcp

The only things left to do (as far as I am concerned) is the ability to save and load list of registers.

**Comment by 5opr4ni** [comment]
I will follow and watch.

**Comment by dimitry-ishenko** [comment]
@5opr4ni it is now fairly usable. In fact you don't have to use the PBus part and can use it as a super simple CCG playout GUI:

snapshot

**Comment by dimitry-ishenko** [comment]
Maybe I should post on in the forums, as I've totally hijacked this thread now :blush:

**Pull request closed without merging**
