### PR TITLE
[html] Upgrade to CEF3239 (Chromium 63)

### PR DESCRIPTION
**Pull request by Julusian**
This upgrades the HTML producer to a more modern version of Chromium (CEF3239 / Chromium 63).

This builds on the work from @AndreasWilladsen and @sesse. Any additional tweaks or tests to run are appreciated. I have labelled this PR as a WIP as performance is not yet perfect and some frames appear to be being lost, however the same is true of the current version

Improvements:
- Newer chromium. Gives new features and makes template dev much easier at it matched current versions of chrome
- Font smoothing
- 3D CSS

Missing:
- WebGL (Pending [CEF #1006](https://bitbucket.org/chromiumembedded/cef/issues/1006))

Forum post: https://casparcg.com/forum/viewtopic.php?f=3&t=4681&p=29526

Builds: https://caspar.julusian.co.uk/cef-upgrade/

### CODE REVIEW

**Comment by jesperstarkar** [comment]
I have briefly tested this on Windows, and it seems to be really really really good.

Also, NRK are using this branch daily on their main channel all days this summer, and have been doing so for some weeks already.

**Comment by sesse** [comment]
@jesperstarkar NRK isn't using this branch; they're using a similar one, but it's not the same. In particular, they're using stock a CEF binary as opposed to a custom build (as well as a bunch of build fixes to get it to e.g. run on something newer than Ubuntu 14.04). I'm sure the OSR patch is useful (and I trust the author to do sane things), but having a custom CEF build means it's going to be a lot more painful to upgrade CEF in the future, and adding patched binaries without the corresponding source code and build scripts used to build them isn't going to fly with the GPL.

**Comment by jesperstarkar** [comment]
@sesse Thank you for both clarifications. Hmm, when something seems to good to be true etc etc.

So basically, this thing can't fly, and you don't have any immediate good ideas on how to make it so?

**Comment by sesse** [comment]
It's unproblematic wrt. the GPL if you include the patched CEF source code and build scripts.

**Comment by jesperstarkar** [comment]
The NRK branch of yours, did that one meet the same performance with the stock CEF?

**Comment by sesse** [comment]
I've never benchmarked them against each other; I hadn't heard of said OSR patch before this PR was updated. I would assume the patched CEF has better performance than stock CEF, although both should be better than the current (stock) CEF in CasparCG.

**Comment by Julusian** [comment]
This is using only the cef related changes from the branch that NRK are using, I thought it best to seperate out the bits needed to increase the chance of this being accepted.

I hadn't thought about the licensing of this, but shall add a patch file and build instructions. As cef is BSD licensed I shall also check if there are other rules that need to be considered there.

I included your branch in the tests I ran, it is the rows labelled 'sesse full' in the spreadsheet linked above.

**Comment by sesse** [comment]
Ah, so “performance” here is about having smooth frame rates, not CPU/GPU resource use per se. Then I can understand that the old one would be better than stock upgraded CEF, indeed; a lot of water has passed under the CEF bridge in the period.

**Comment by jesperstarkar** [comment]
The main objective of a CEF upgrade is to have modern web capabilites: font smoothing, killing the SVG-font hack, CSS3 3D transforms etc. 

When it comes to performance, frame rate should be a higher priority than resource usage, IMO, as you can't use something that's dropping frames, and more resources can be bought for more money.

**Comment by sesse** [comment]
Yes, but part of what the patch in question does is to _reduce_ the frame rate at the right times, so that it doesn't go over and need to drop frames.

**Comment by Julusian** [comment]
I agree with Jesper, and so my main focus has been on frame rate rather than resource usage.

What do you mean? I can see that we are now specifying the framerate to use for the rendering in cef, is that what you are referring to?

**Comment by sesse** [comment]
@Julusian It's mostly about how the CEF patch works; it's not important. I just wanted to understand what was meant by performance in this context.

**Comment by dotarmin** [comment]
I'm currently on vacation and I'llbe back in late August. @jesperstarkar has already Skyped me about this PR, it looks interesting and would be a huge boost for CasparCG Server. I will check if their is anybody that could throw some eyes on this PR before I'm back from my vacation.

Thanks for the PR!

Best regards,
Armin

**Comment by ax25** [comment]
Hi all!

I'm testing this version. I found that in my case it is impossible to run some HTML templates. For instance, the example from Niclas (https://casparcg.com/forum/viewtopic.php?f=5&t=4522) makes the server to crush:

> [0802/123203.144:ERROR:gles2_cmd_decoder.cc(9709)] [.DisplayCompositor-0000020B4AD0D7D0]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.
[0802/123203.184:ERROR:gles2_cmd_decoder.cc(15567)] Context lost because SwapBuffers failed.
[0802/123203.184:ERROR:gles2_cmd_decoder.cc(5318)] Error: 5 for Command kPostSubBufferCHROMIUM
[0802/123203.185:ERROR:gpu_channel_manager.cc(188)] Exiting GPU process because some drivers cannot recover from problems.

My testing setup: _Win 10 - i7-5820k - GTX 970 (Driver version 382.05) - Decklink Quad2

The template uses GSAP libraries, this seems to make the difference, as other templates that don't use the library seem to work nicely.

**Comment by Punkley** [comment]
There are a few reports of this on the cef forums for background rendering

Does it crash if you use --disable-gpu ?

**Comment by Punkley** [comment]
I've found an interesting issues over th weekend with this actually.

I have a stand alone server, it boots up and runs caspercg on boot, if it does this it uses the opengl on the video card (as expected).
What was happening however was when I loaded an HTML page on my decklink duo 2 it wouldn't display.

However if I RDP'ed into the box restarted CasperCG, this would load it without OpenGL, it would then work as expected. I suspect there is something a little odd going on with opengl enabled on decklinks.

Kingsley

**Comment by yannisgu** [comment]
For the record. The CEF PR used here hase been rebased and a new PR was created here: https://bitbucket.org/chromiumembedded/cef/pull-requests/131/osr-fix-gpu-cpu-readback-performance/diff

**Comment by itodorovic** [comment]
Thank you yannisgu! Hope they will accept the PR quickly.

**Comment by ronag** [comment]
@itodorovic I will look into this next month.

**Comment by Julusian** [comment]
@yannisgu I shall update this PR to use that new version along with a newer version of cef hopefully later this week once I have access to my dev machine.

@ronag let me know if you want a specific branch/version of cef.

**Comment by ronag** [comment]
@Julusian I think you are more up to date on CEF than me.

**Comment by Julusian** [comment]
The CEF PR has now been merged into CEF 3239 (Chromium 63).
Chromium 63 has just been released as stable, so as soon as CEF promotes 3239 to stable, I shall update this PR with that build. Hopefully it wont take long for that to happen.
If anyone wants a build to play with I can provide one for a beta version of CEF, but I dont think it appropriate to consider merging that when stable should be not far away

**Comment by itodorovic** [comment]
Finally! 
We have been waiting for several years for this, we can wait a few weeks more IMHO, no need for beta immediately.

**Comment by Pimpmuckl** [comment]
@Julusian if you have some time by any chance, would you mind uploading the PR from 3239? Would be greatly appreciated for some testing here

**Comment by Julusian** [comment]
Just waiting on a 'CEF 3.3239.1701.g68fddae / Chromium 63.0.3239.109' for Windows x64 to be available on http://opensource.spotify.com/cefbuilds/index.html before updating.
If you want to test with the previous build of CEF (has the OSR patch applied, but still a beta chromium) I can quickly throw that together for you

**Comment by Pimpmuckl** [comment]
@Julusian don't want to make you spend extra time! Your work is greatly appreciated as is, I'll gladly spend the few days waiting :)

**Comment by Julusian** [comment]
I have pushed an update to this pr to update to cef 3239.
I havent done much testing yet, but am looking at it now. 
I am having an issue running it with the nvidia 384 drivers on ubuntu 14.04, but it appears to works on both windows 10 with nvidia 388 and debian 9 with intel hd 5500.
Builds are available at: https://caspar.julusian.co.uk/cef-upgrade/

**Comment by ronag** [comment]
@Julusian please let me know you feel this is ready for merge and I will start looking into it.

**Comment by Julusian** [comment]
OK. Another version pushed. This one now runs fine on ubuntu with nvidia. I had to compile cef myself for it to work, which is very strange so I shall raise this on their forums.
I shall do some more testing tomorrow, but so far I am happy with it on both windows and linux. Any additional testing would be much appreciated.
https://caspar.julusian.co.uk/cef-upgrade/

**Comment by ax25** [comment]
Tested julusian version, html rendering is very very slow and problematic. Simple animations are rendered with a lot of problems. Sorry I can't give more details.

**Comment by MauriceVeraart** [comment]
Did a rather quick check with a pretty large HTML template I am working on on the moment.
I have the feel it loads faster ! On the other hand I did load some example pages from three.js and I am seeing some stutter. and a lot of "spiking" in diag on "BrowserTickTime"
build f15ba601fe06a7f57512c14c5958cadebf56d970
  
latestbuild

your build

julusian

hope this gives you some clue's on whats going on.
thanks for the hardwork by the way

**Comment by Pimpmuckl** [comment]
I have a similar problem where a simple js/css animation sometimes plays out ridiculously fast and sometimes in the correct speed. I've seen this with all builds in this thread though and it's not specific to the current build, this one just doesn't "fix" it.

In general, the performance is much better, but when I compare simple js animation smoothness from 2.1.0 Beta 2 from April 13th, it's a significant difference.

April build:
[img]https://i.imgur.com/qefkVQd.png[/img]

Current CEF build:
[img]https://i.imgur.com/VQPZT6G.png[/img]

**Comment by 5opr4ni** [comment]
I think you have to share how you do the drawing before we can evaluate if your test are relevant. 
There are several ways of doing animations and things depends on what is driving the frames timingwise.
Maybe we should make some sort of test-scheme.

**Comment by Pimpmuckl** [comment]
There's something wrong with the webm playout that directly seems to correlate with the "timing" I've mentioned above.

- Sometimes a simple webm playout would be immensely sped up (if `--off-screen-rendering-enabled --off-screen-frame-rate=60` is set) or exceedingly croppy. The diag window then looks like [this](https://i.imgur.com/PWT64hd.png) compared to a normal (and smooth) playout like [this](https://i.imgur.com/hhDUTAK.png).
- If I set the Caspar server to 29.97 fps, the webm playout is half speed. OBS' CEF works correctly in that regard.
- There seems to be a weird interaction between the monitor's refresh rate, caspar playout fps and CEF. CEF tries to render up to the monitors' refresh rate instead of the fps caspar is set to, even if I specify `--off-screen-frame-rate=60`.
- If the "speed up" bug happens that playout is sped up, it's the same speed on the 29.97 server as it is on the 59.94 server.

I made a [test page](https://gigamove.rz.rwth-aachen.de/download/id/mLFwE98BA3B5xo) that plays a webm. Simply throw that on a local server and add `http://127.0.0.1:8080/Files/webm.html` to the client as HTML source and after a couple of F2-restarts (~sometimes takes 15-25 tries), there should be [this pattern](https://i.imgur.com/PWT64hd.png) and weird playout. It occurs way more often on the page we use where the playout is called via websocket but I can't really replicate this right now.

**Comment by Lange** [comment]
Chrome in general has significant issues when the system has displays with multiple refresh rates attached. For instance, having a 120hz monitor and a 60hz monitor present and having Chrome windows open on both can create interesting and unexpected rendering performance issues. The issues are alleviated when all windows are on the same monitor, especially if that monitor is the highest refresh rate monitor present.

I'm unsure what the rendering pipeline is like for this particular usage of CEF, but if its relying on vsync for frame timings then that may be part of the issue. My understanding is that implementations in other software such as OBS do not rely on vsync for their frame timings, but please fact-check me on that as I am not 100% certain.

@Pimpmuckl Do your results change when using any of the following flags?
-  `--disable-gpu-vsync`
-  `--disable-gpu-vsync=gpu`
-  `--disable-gpu-vsync=beginframe`

**Comment by Julusian** [comment]
After playing around with this for a few hours today and I have found a pretty major issue.
I've mostly been using https://www.testufo.com/animation-time-graph as it gives some useful information on timings along with an animation.
In desktop chrome and 2.1beta2 I am getting a pretty consistent timing within 2ms with the occasional blip outside of that. In my builds, that range is much wider, sitting at 7ms with a fair number more outside of that range.
After digging into some of the code, I added a new value to the diag graphs to show when cef failed to deliver a frame to caspar. (called browser-dropped-frame shown in red)
2.1beta2: https://imgur.com/LDNy8WG
ec2a1836: https://imgur.com/xA5W2Nl  https://imgur.com/GmtI74n
It is worth noting that even beta2 drops the occasional frame, but ec2a1836 can nowhere near cope when running more than 1 template. 
I dug in further and have found that when running 1 template, 65% of the cpu time is spent in the CEF message loop, 5% of which is calling back into our OnPaint handler with almost all of the rest spent copying around pixel buffers. If I add a second template, then the overall cpu increases such that the 56% used by the CEF message loop now accounts for a whole cpu core.
The CEF message loop is a single thread, and so appears to become a big bottleneck with all the pixel copying. Seems strange that it would be the case though.

**Comment by Julusian** [comment]
@Lange We shouldn't be relying on vsync and are already setting disable-gpu-vsync internally. More than anything we appear to be relying on the timing of calling requestAnimationFrame in the loaded page to get new frames. We are currently triggering a render of queued animations from requestAnimationFrame whenever caspar consumes a frame. If I change it to so that cef runs that itself at a regular interval my frame timing drops down to averaging within 2ms of the target time but still stutters horrendously (perhaps even worse) when running multiple templates.

**Comment by Lange** [comment]
@Julusian Ah okay, thank you for the additional information.

Also, does using `multi_threaded_message_loop` help the issue you described ([docs](https://bitbucket.org/chromiumembedded/cef/wiki/GeneralUsage#markdown-header-message-loop-integration))? Note that it does not work on OSX ([source](https://bitbucket.org/chromiumembedded/cef/issues/745/multi_threaded_message_loop-yes-on-mac-os)).

**Comment by Julusian** [comment]
@Lange No, I tried setting that and it didnt seem to help. 
Im going to have a look at obs does, then I shall check if the situation is the same on linux.

**Comment by Julusian** [comment]
In obs with cef 3239 and ```--enable-gpu``` and ```.\cefclient.exe --off-screen-rendering-enabled --off-screen-frame-rate=60``` they both report similarly bad timings in the same template. By removing ```--enable-gpu``` they both perform a lot smoother.
I'll look into it further tomorrow.

**Comment by Lange** [comment]
@Julusian [CEF issue #1006](https://bitbucket.org/chromiumembedded/cef/issues/1006) may be relevant. In particular, a community member recently started work on experimental builds of CEF which support rendering directly to a texture provided by the client, eliminating the extra round-trip needed by the current rendering pipeline. Check the most recent posts in that issue thread for more details.

**Comment by Julusian** [comment]
@Lange haha yes, I was just about to set my machine downloading chromium so I could attempt to build that in the morning. Even though in caspar we need the frames to be cpu side, that might help in hopefully that work can be sent to other threads

**Comment by Julusian** [comment]
Another test with ec2a183 in PAL reveals that I can run 3 templates at once without any noticeable degradation and keeping the time within 2ms of target. Adding a fourth causes the tick times and animation times to increase noticably. This looks to agree with my theory that the bitmap copying from gpu to cpu is a bottleneck.
As OBS appears to be able to do multiple smooth animations with gpu disabled in cef 2987, I have tried to compile using that version but keep getting some weird visual studio errors. I may give this another try later on, as it looks like a good starting point.
@Lange the patch from [CEF #1006](https://bitbucket.org/chromiumembedded/cef/issues/1006) has a pretty bad conflict with 3239, so I've put that to one side to look at later on. It's too experimental to make it into 2.1.0, so there isn't any rush to look at it. 
Im going to have limited access to a machine that can build and run caspar until the new year, but I shall keep looking at this when I can

**Comment by wifinityes** [comment]
Hi Julusian,

I was checking your linux build and is working very well. I did some changes in the ffmpeg consumer module and another changes in the casparcg source code, and I'd like apply your new CEF version to my casparcg source in order to compile my custom version with your CEF. Can you guide me, how do it? Thank you very much for your excellent work.

**Comment by sesse** [comment]
@wifinityes, the simplest thing is probably to rebase your branch on his PR. Assuming you have your changes as a commit (or series of commits) in your git repository, you can do

git remote add julusian https://github.com/Julusian/CasparCG-Server
git rebase julusian/cef_upgrade

**Comment by ronag** [comment]
@Julusian do you know if CEF has made any progress on cross context OGL buffer transfer? Currently, even if CEF itself is GPU accelerated we have to copy (device -> host -> host -> device) every frame which is very inefficient. If we could get cross context transfers we would have 0 overhead which would probably resolve most if not all performance related issues.

Last time I looked they used pbuffers which are not optimal for this...

**Comment by Julusian** [comment]
@ronag That is what Lange and I were discussing above with [CEF #1006](https://bitbucket.org/chromiumembedded/cef/issues/1006). Someone has made a windows only prototype for doing that, but doesn't look like anything will be ready in time for 2.1.0.
Yes, it looks like all that copying is what is causing my performance issues. I think it is using pbuffers still.

**Comment by sesse** [comment]
GPU copying in itself is fairly cheap (modern GPUs have dedicated copy engines that can work in parallel with everything else), but CPU copying can be costly, and the CPU spin-waiting on the GPU to be done copying certainly isn't cheap. You'll usually need one GPU readback in _some_ form, though, assuming that you want SDI output and not just display.

In general, Caspar is too oriented around synchronous copying (and thus waiting); see #603.

**Comment by wifinityes** [comment]
Thanks @sesse for your help,

I have my custom build using the CEF 3.3239.1705 upgrade.

Thanks @Julusian for your great work!

**Comment by Julusian** [comment]
I have pushed another update to this PR. This change sets the disable-gpu flag. This allows me to run 4 of the ufo test simultaneously, or 5 with minor stuttering. Above that it really starts to struggle. This matches what I can in 2.1b2 and then degrades more gracefully from this point. https://imgur.com/a/CKL9j
I have also tested this on ubuntu14.04 and get the same trends although it can run 1 template less without struggling.

This does mean that webgl is also still unavailable. 3D css does work, but without the gpu it can struggle in complex scenes. This isnt ideal, but I think it is the best we can do with current CEF, and is better than before

Currently the build of CEF I have been using do not have proprietry_codecs (h264, mp3) enabled. The automated CEF builds do not have these enabled for licensing reasons, but as it uses ffmpeg and we already allow both of these codecs via the ffmpeg producer I personally dont see any harm in using a build with those enabled. @ronag what do you think?

I have also added another commit which fixes a bunch of odd bugs i found in the producer while testing.

@Pimpmuckl I have just tested out webm myself with this latest version and it looks to be playing smoothly. The diag graphs look very unhappy but I I know that in chromium any paint updates are accompanied with a dirty rectangle (the region that has changed) to avoid redrawing static parts, so it would make sense that our paint handler doesnt get called if nothing has changed. Looking at any page with no motion causes the diag graphs to become a mess in the same way.

I am now happy with how this is performing (within the known no webgl limitation) relative to 2.1beta2. I shall be keeping an eye on [CEF #1006](https://bitbucket.org/chromiumembedded/cef/issues/1006) and once there is something that looks useable I shall get some builds on a new PR so that we can hopefully get webgl working sometime soon

**Comment by jesperstarkar** [comment]
Thank you for your efforts @Julusian, highly appreciated. This is exciting!

**Comment by baltedewit** [comment]
Getting the following error in linux after keeping a template open for a few minutes.

```
[0109/084502.122481:FATAL:cef_ref_counted.h(333)] Assert failed: ptr_ != __null. 

#0 0x7f1e3f4dc207 base::debug::StackTrace::StackTrace()
#1 0x7f1e3f4f2ce1 logging::LogMessage::~LogMessage()
#2 0x7f1e3f40f32c cef_log
#3 0x000000bfa7dc cef::logging::LogMessage::~LogMessage()
#4 0x000000bc0d35 scoped_refptr<>::operator->()
#5 0x000000bc8681 caspar::html::html_producer::on_interaction()
#6 0x000000a1af5b caspar::core::interaction_aggregator::translate_and_send()
#7 0x000000a24ced _ZZN6caspar4core5stage4implclERKNS0_17video_format_descEENKUlvE_clEv
#8 0x000000a2520a _ZNSt17_Function_handlerIFSt3mapIiN6caspar4core10draw_frameESt4lessIiESaISt4pairIKiS3_EEEvESt17reference_wrapperISt12_Bind_simpleIFSC_IZNS1_8executor21internal_begin_invokeIZNS2_5stage4implclERKNS2_17video_format_descEEUlvE_EESt6futureIDTclfp_EEEOT_NS1_13task_priorityEEUlvE_EvEEEE9_M_invokeERKSt9_Any_data
#9 0x000000a1b9af std::_Function_handler<>::_M_invoke()
#10 0x0000008c540e std::__future_base::_State_base::_M_do_set()
#11 0x7f1e3a9d9a99 __pthread_once_slow
#12 0x0000008f8850 _ZSt9call_onceIMNSt13__future_base11_State_baseEFvRSt8functionIFSt10unique_ptrINS0_12_Result_baseENS4_8_DeleterEEvEERbEJKPS1_St17reference_wrapperIS8_ESF_IbEEEvRSt9once_flagOT_DpOT0_
#13 0x000000a09c2d std::__future_base::_State_base::_M_set_result()
#14 0x000000a41605 _ZNSt13__future_base11_Task_stateIZN6caspar8executor21internal_begin_invokeIZNS1_4core5stage4implclERKNS4_17video_format_descEEUlvE_EESt6futureIDTclfp_EEEOT_NS1_13task_priorityEEUlvE_SaIiEFSt3mapIiNS4_10draw_frameESt4lessIiESaISt4pairIKiSK_EEEvEE6_M_runEv
#15 0x000000a1a6b0 _ZNSt17_Function_handlerIFvvEZN6caspar8executor21internal_begin_invokeIZNS1_4core5stage4implclERKNS4_17video_format_descEEUlvE_EESt6futureIDTclfp_EEEOT_NS1_13task_priorityEEUlvE0_E9_M_invokeERKSt9_Any_data
#16 0x000000918154 caspar::executor::run()
#17 0x000000ca43cf thread_proxy
#18 0x7f1e3a9d26ba start_thread
#19 0x7f1e397c73dd clone

Received signal 6
#0 0x7f1e3f4dc207 base::debug::StackTrace::StackTrace()
#1 0x7f1e3f4dbd6f base::debug::(anonymous namespace)::StackDumpSignalHandler()
#2 0x7f1e3a9dc390 <unknown>
#3 0x7f1e396f5428 gsignal
#4 0x7f1e396f702a abort
#5 0x7f1e3f4da5b2 base::debug::BreakDebugger()
#6 0x7f1e3f4f30ca logging::LogMessage::~LogMessage()
#7 0x7f1e3f40f32c cef_log
#8 0x000000bfa7dc cef::logging::LogMessage::~LogMessage()
#9 0x000000bc0d35 scoped_refptr<>::operator->()
#10 0x000000bc8681 caspar::html::html_producer::on_interaction()
#11 0x000000a1af5b caspar::core::interaction_aggregator::translate_and_send()
#12 0x000000a24ced _ZZN6caspar4core5stage4implclERKNS0_17video_format_descEENKUlvE_clEv
#13 0x000000a2520a _ZNSt17_Function_handlerIFSt3mapIiN6caspar4core10draw_frameESt4lessIiESaISt4pairIKiS3_EEEvESt17reference_wrapperISt12_Bind_simpleIFSC_IZNS1_8executor21internal_begin_invokeIZNS2_5stage4implclERKNS2_17video_format_descEEUlvE_EESt6futureIDTclfp_EEEOT_NS1_13task_priorityEEUlvE_EvEEEE9_M_invokeERKSt9_Any_data
#14 0x000000a1b9af std::_Function_handler<>::_M_invoke()
#15 0x0000008c540e std::__future_base::_State_base::_M_do_set()
#16 0x7f1e3a9d9a99 __pthread_once_slow
#17 0x0000008f8850 _ZSt9call_onceIMNSt13__future_base11_State_baseEFvRSt8functionIFSt10unique_ptrINS0_12_Result_baseENS4_8_DeleterEEvEERbEJKPS1_St17reference_wrapperIS8_ESF_IbEEEvRSt9once_flagOT_DpOT0_
#18 0x000000a09c2d std::__future_base::_State_base::_M_set_result()
#19 0x000000a41605 _ZNSt13__future_base11_Task_stateIZN6caspar8executor21internal_begin_invokeIZNS1_4core5stage4implclERKNS4_17video_format_descEEUlvE_EESt6futureIDTclfp_EEEOT_NS1_13task_priorityEEUlvE_SaIiEFSt3mapIiNS4_10draw_frameESt4lessIiESaISt4pairIKiSK_EEEvEE6_M_runEv
#20 0x000000a1a6b0 _ZNSt17_Function_handlerIFvvEZN6caspar8executor21internal_begin_invokeIZNS1_4core5stage4implclERKNS4_17video_format_descEEUlvE_EESt6futureIDTclfp_EEEOT_NS1_13task_priorityEEUlvE0_E9_M_invokeERKSt9_Any_data
#21 0x000000918154 caspar::executor::run()
#22 0x000000ca43cf thread_proxy
#23 0x7f1e3a9d26ba start_thread
#24 0x7f1e397c73dd clone
  r8: 00007f1e09266a50  r9: 00007f1e09268700 r10: 0000000000000008 r11: 0000000000000202
 r12: 00007f1e09266ea0 r13: 0000000000000052 r14: 00007f1e09266e98 r15: 00007f1e09266e90
  di: 00000000000003b9  si: 00000000000003e0  bp: 00007f1e09266a50  bx: 00007f1e09266a50
  dx: 0000000000000006  ax: 0000000000000000  cx: 00007f1e396f5428  sp: 00007f1e092668a8
  ip: 00007f1e396f5428 efl: 0000000000000202 cgf: 002b000000000033 erf: 0000000000000000
 trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.
```

Template contains a webm video with alpha channel, and and svg. animations through animejs.
This error is not appended to log file, just to console.
OS is Ubuntu 16.04, machine is an xps 9560.

I am also getting a few of the errors below, but they don't seem to hurt anyone:
```
[0109/084329.252598:ERROR:object_proxy.cc(573)] Failed to call method: org.gnome.SessionManager.Uninhibit: object_path= /org/gnome/SessionManager: org.gnome.SessionManager.GeneralError: Unable to uninhibit: Invalid cookie
[0109/084329.253476:ERROR:power_save_blocker_x11.cc(408)] No response to Uninhibit() request!
```

**Comment by Julusian** [comment]
@baltedewit do you consistently get this issue? I cant reproduce it on Ubuntu 14.04 myself.
I have attempted a fix based on the stack trace you posted, are you able to try it with this build? https://caspar.julusian.co.uk/cef-upgrade-potential-fix/
Interestingly the stack trace suggests it is an issue with interaction being sent to a destroyed html producer. Does this sound correct based on what you had been doing?

**Comment by baltedewit** [comment]
I have tried your patch, and confirmed that this is an issue in the interaction module. It only occurs in this specific template.

Steps to reproduce:

1. CG PLAY the template
2. CG STOP the template
3. Click anywhere in the screen consumer

In your latest patch however, it will crash after step 2. But it will not crash at all if I play other templates or just a plain HTML page.

I have uploaded the full template, including dependencies, here: https://balte.stackstorage.com/s/8c2z7vAjTohKTSf

**Comment by Julusian** [comment]
@baltedewit Thanks for posting the template and STR, that made it really easy to find the issue.

A new build that fixes this will be up soon: https://caspar.julusian.co.uk/cef-upgrade/

**Comment by ronag** [comment]
This PR is not closed. However, we've force pushed the 2.1.0 branch in order to convert the history to LFS. Hopefully this should reduce the repo size from several gigs to a several megs.

@Julusian just keep working and I will cherry-pick this into 2.1.0.

**Comment by Julusian** [comment]
@ronag This is ready for you to take a look at. I am happy with it and it has been running fine in my testing.

**Comment by ronag** [comment]
@Julusian perfect. It's on my list for next week.

**Comment by baltedewit** [comment]
Would it be non-trivial to have gpu acceleration as an option in the config file?
There are some projects/ideas where we don't want to give up on WebGL.

**Comment by Julusian** [comment]
That should be simple enough to do. I shall give it a go tonight.

**Comment by Julusian** [comment]
@baltedewit I have done that now. Build should be up in ~10 minutes

**Comment by ronag** [comment]
@Julusian does this fix https://github.com/CasparCG/Server/issues/523?

**Comment by ronag** [comment]
@Julusian Could you do a new PR based 2.2.0?

**Comment by Julusian** [comment]
Im not sure, I havent tested on any distro other than ubuntu 14.04.
Yes, I can rebase this then check it on 16.04, which is what someone had that issue on

**Comment by baltedewit** [comment]
Can confirm this issue is still apparent on 16.04, the modification to the
run script also still works.

**Comment by Julusian** [comment]
> Can confirm this issue is still apparent on 16.04, the modification to the run script also still works.

OK, then it should really be added to the run script as 16.04 is now the supported version. I can do that whilst rebasing

**Comment by ronag** [comment]
I'll merge ASAP there is a PR for 2.2.0. Could u do the same with https://github.com/CasparCG/Server/pull/644?

**Comment by Julusian** [comment]
sure. Ill do it as one PR for them both then

**Comment by ronag** [comment]
@Julusian https://bitbucket.org/chromiumembedded/cef/pull-requests/131/osr-fix-gpu-cpu-readback-performance/diff

**Comment by Julusian** [comment]
Yes, It was merged before I updated to CEF3239. It partially helped, but there is now a bottleneck within cef where it pulls frames from the gpu. 
https://bitbucket.org/chromiumembedded/cef/issues/1006 looks to be another issue to watch to solve that

**Comment by pascoual** [comment]
@Julusian seem that the chromium Pull Request / Issue 1006 was manually merged one week ago.

**Support external textures in OSR mode - revisted (issue #1006)**
> Marshall Greenblatt
This PR has been manually merged in master revisions 713eebc and 1e6b870 with minor style and documentation fixes.
Please create issues in the CEF issue tracker for any remaining problems related to this PR.

[See here](https://bitbucket.org/chromiumembedded/cef/pull-requests/158/support-external-textures-in-osr-mode/diff#comment-77336640).

**Comment by Julusian** [comment]
@pascoual that is good to hear.

However as the latest stable release of CEF/Chromium is 69, we probably still want to wait until it is stable before we use it (unless we want to use a custom built copy of CEF). Hopefully I will have some time soon to give it a try though

**Comment by pascoual** [comment]
@juliusian Chromium 71 seem to be released as stable  :).

**Pull request closed without merging**
