### PR TITLE
ffmpeg_producer rewrite

### PR DESCRIPTION
**Pull request by ronag**
- FFMMPEG 3.4.1
- Replace custom implementations with FFMPEG filters and utils
- Fixed timestamp handling
- Fixed V/A sync
- Fixed looping
- Fixed seeking
- Fixed duration
- Improved stability
- Improved performance
- Audio resampling to match timestamps
- Fixed invalid interlaced YUV (411, 420) handling
- Added YUVA444, YUVA422 support
- Added IO timeout
- Added HTTP reconnect
- Significantly improved auto conversion (fps, field mode, scaling etc..). Should play "anything"
- FFMPEG video filter support
- FFMPEG audio filter support
- CALL SEEK returns actually seeked value (useful during relative seeking)
- All AMCP timings (seek, duration, in, out etc...) is based on the channel format
- Removed "frame-number" and "nb-frames" from INFO response. They make no sense. Use "file-" versions instead
- Misc minor fixes, improvements, and cleanup

# TODO 1
- [x] INFO  
- [x] OSC
- [x] LOOP
- [x] CALL SEEK (latest wins, update current frame)
- [x] Auto merge multiple audio tracks (e.g. some mxf)
- [x] Secondary video stream is alpha
- [x] Linux Build

# TODO 2

- [ ] option for default filter override
- [ ] CALL VFILTER
- [ ] CALL AFILTER

# TODO 3

- [ ] ts discontinuity
- [x] variable framerate input
- [ ] timeout & retry
- [ ] further improvements to duration (use actual duration when looping)
- [ ] edge cases when input start_time is not set?
- [ ] What if audio & video pts from input is out of sync / discontinious?
- [x] Use separate threads for audio decoding, video decoding, audio filter, video filter
- [x] pixel_constraints(). What is this?
- [ ] Move more stuff to GPU (nice to have)
- [ ] vid_params

# TODO 4

- [ ] custom_channel_order
- [ ] FRAMERATE
- [ ] thread priorities
  
# Binaries

# Notes

Only debug build will currently compile.
  
  
  Moved from https://github.com/nxtedition/caspar/pull/3

### CODE REVIEW

**Comment by ronag** [comment]
Ready for testing. @TomKaltz @5opr4ni @dotarmin @jesperstarkar @premultiply

Should also build on Linux. Though I'm not providing binaries here for that.

[CasparCG 2.2.0](https://www.dropbox.com/s/9wh9wy6fn1tw41j/CasparCG%202.2.0.zip?dl=0)

**Comment by dotarmin** [comment]
I will try it out right away! 😄

**Comment by premultiply** [comment]
Testing... :-)

First quick impressions:
- Does only play a little few files from my archive.
- Interlaced files show a field-freeze on the first frame.
- Deinterlacing and Scaling Quality looks better.

There seems to be something wrong with at least with files with more then one audio track:

`[2018-01-24 15:35:45.306] [1028] [info]    Received message from 127.0.0.1: LOADBG 1-10 "1001-V1_HDF01A-CONFORM_25S" CUT 0 Linear RIGHT\r\n
[2018-01-24 15:35:45.328] [3052] [error]   [ffmpeg] [amerge @ 00000000155BD9C0] [Eval @ 0000000014E192C0] Invalid chars 'null' at the end of expression '8anull'
[2018-01-24 15:35:45.328] [3052] [error]   
[2018-01-24 15:35:45.328] [3052] [error]   [ffmpeg] [amerge @ 00000000155BD9C0] Unable to parse option value "8anull"
[2018-01-24 15:35:45.328] [3052] [error]   
[2018-01-24 15:35:45.328] [3052] [error]   [ffmpeg] [amerge @ 00000000155BD9C0] [Eval @ 0000000014E19330] Invalid chars 'null' at the end of expression '8anull'
[2018-01-24 15:35:45.328] [3052] [error]   
[2018-01-24 15:35:45.328] [3052] [error]   [ffmpeg] [amerge @ 00000000155BD9C0] Unable to parse option value "8anull"
[2018-01-24 15:35:45.328] [3052] [error]   
[2018-01-24 15:35:45.329] [3052] [error]   [ffmpeg] [amerge @ 00000000155BD9C0] Error setting option inputs to value 8anull.
[2018-01-24 15:35:45.329] [3052] [error]   
[2018-01-24 15:35:45.329] [3052] [error]   [ffmpeg] [Parsed_amerge_0 @ 0000000016AABC00] Error applying options to the filter.
[2018-01-24 15:35:45.329] [3052] [error]   
[2018-01-24 15:35:45.329] [3052] [error]   [ffmpeg] [AVFilterGraph @ 00000000155B1440] Error initializing filter 'amerge'
[2018-01-24 15:35:45.329] [3052] [error]   [ffmpeg]  with args 'inputs=8anull'
[2018-01-24 15:35:45.329] [3052] [error]   [ffmpeg] 
[2018-01-24 15:35:45.329] [3052] [error]   
[2018-01-24 15:35:45.329] [3052] [error]   [ffmpeg] [amerge @ 00000000155BD9C0] [Eval @ 0000000014E192C0] Invalid chars 'null' at the end of expression '8anull'
[2018-01-24 15:35:45.329] [3052] [error]   
[2018-01-24 15:35:45.329] [3052] [error]   [ffmpeg] [amerge @ 00000000155BD9C0] Unable to parse option value "8anull"
[2018-01-24 15:35:45.329] [3052] [error]   
[2018-01-24 15:35:45.329] [3052] [error]   [ffmpeg] [amerge @ 00000000155BD9C0] [Eval @ 0000000014E19330] Invalid chars 'null' at the end of expression '8anull'
[2018-01-24 15:35:45.329] [3052] [error]   
[2018-01-24 15:35:45.329] [3052] [error]   [ffmpeg] [amerge @ 00000000155BD9C0] Unable to parse option value "8anull"
[2018-01-24 15:35:45.329] [3052] [error]   
[2018-01-24 15:35:45.329] [3052] [error]   [ffmpeg] [amerge @ 00000000155BD9C0] Error setting option inputs to value 8anull.
[2018-01-24 15:35:45.329] [3052] [error]   
[2018-01-24 15:35:45.329] [3052] [error]   [ffmpeg] [Parsed_amerge_0 @ 0000000016AABC00] Error applying options to the filter.
[2018-01-24 15:35:45.329] [3052] [error]   
[2018-01-24 15:35:45.329] [3052] [error]   [ffmpeg] [AVFilterGraph @ 00000000155B1440] Error initializing filter 'amerge'
[2018-01-24 15:35:45.329] [3052] [error]   [ffmpeg]  with args 'inputs=8anull'
[2018-01-24 15:35:45.329] [3052] [error]   [ffmpeg] 
[2018-01-24 15:35:45.329] [3052] [error]   
[2018-01-24 15:35:45.333] [3052] [error]   M:\Server4\modules\ffmpeg\producer2\av_producer.cpp(595): Throw in function __cdecl caspar::ffmpeg2::Filter::Filter(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,const struct caspar::ffmpeg2::Input &,__int64,enum AVMediaType,const struct caspar::core::video_format_desc &)
[2018-01-24 15:35:45.333] [3052] [error]   Dynamic exception type: class boost::exception_detail::clone_impl<struct caspar::ffmpeg2::ffmpeg_error_t>
[2018-01-24 15:35:45.333] [3052] [error]   std::exception::what: Unknown exception
[2018-01-24 15:35:45.333] [3052] [error]   [struct boost::errinfo_api_function_ * __ptr64] = avfilter_graph_parse2(graph.get(), filter_spec.c_str(), &inputs, &outputs)
[2018-01-24 15:35:45.333] [3052] [error]   22, "Invalid argument"Caught at (AMCPCommandQueue Channel 1 for TCP Port 5250):
[2018-01-24 15:35:45.333] [3052] [error]   
[2018-01-24 15:35:45.333] [3052] [error]       000000013FB0560D (casparcg): (filename not available): (function-name not available)
[2018-01-24 15:35:45.333] [3052] [error]       000000013FACF9BC (casparcg): (filename not available): (function-name not available)
[2018-01-24 15:35:45.333] [3052] [error]       000000013FF74DBB (casparcg): (filename not available): (function-name not available)
[2018-01-24 15:35:45.333] [3052] [error]       000007FEF660C1E0 (VCRUNTIME140): (filename not available): _C_specific_handler
[2018-01-24 15:35:45.333] [3052] [error]       000007FEF6602D03 (VCRUNTIME140): (filename not available): _TypeMatch
[2018-01-24 15:35:45.333] [3052] [error]       0000000077A3B681 (ntdll): (filename not available): RtlRestoreContext
[2018-01-24 15:35:45.333] [3052] [error]       000000013FB15A28 (casparcg): (filename not available): (function-name not available)
[2018-01-24 15:35:45.333] [3052] [error]       000000013FB18C1C (casparcg): (filename not available): (function-name not available)
[2018-01-24 15:35:45.333] [3052] [error]       000000013FB17D23 (casparcg): (filename not available): (function-name not available)
[2018-01-24 15:35:45.333] [3052] [error]       000000013FC73A58 (casparcg): (filename not available): (function-name not available)
[2018-01-24 15:35:45.333] [3052] [error]       000000013FC579EC (casparcg): (filename not available): (function-name not available)
[2018-01-24 15:35:45.333] [3052] [error]       000000013FCBF50D (casparcg): (filename not available): (function-name not available)
[2018-01-24 15:35:45.333] [3052] [error]       000000013FCBE389 (casparcg): (filename not available): (function-name not available)
[2018-01-24 15:35:45.333] [3052] [error]       000000013FCBFDFA (casparcg): (filename not available): (function-name not available)
[2018-01-24 15:35:45.333] [3052] [error]       000000013FAAD038 (casparcg): (filename not available): (function-name not available)
[2018-01-24 15:35:45.333] [3052] [error]       000000013FCBEA95 (casparcg): (filename not available): (function-name not available)
[2018-01-24 15:35:45.333] [3052] [error]       000000013FABA1C3 (casparcg): (filename not available): (function-name not available)
[2018-01-24 15:35:45.333] [3052] [error]       000000013FE957B3 (casparcg): (filename not available): (function-name not available)
[2018-01-24 15:35:45.333] [3052] [error]       000007FEE882BEED (ucrtbase): (filename not available): crt_at_quick_exit
[2018-01-24 15:35:45.333] [3052] [error]       00000000778E59CD (kernel32): (filename not available): BaseThreadInitThunk
[2018-01-24 15:35:45.333] [3052] [error]       0000000077A1A561 (ntdll): (filename not available): RtlUserThreadStart
[2018-01-24 15:35:45.333] [3052] [error]   
[2018-01-24 15:35:45.388] [3052] [error]   No match found for supplied commands. Check syntax. Turn on log level debug for stacktrace.
[2018-01-24 15:35:45.388] [3052] [info]    Sent message to 127.0.0.1:404 LOADBG FAILED\r\n
[2018-01-24 15:35:46.760] [1028] [info]    Received message from 127.0.0.1: PLAY 1-10\r\n
[2018-01-24 15:35:46.760] [3052] [info]    Sent message to 127.0.0.1:202 PLAY OK\r\n`

I will continue testing tomorrow.

**Comment by ronag** [comment]
@premultiply could you provide me with the files that don't work?

**Comment by ronag** [comment]
@premultiply your error should be fixed

[CasparCG 2.2.0](https://www.dropbox.com/s/9wh9wy6fn1tw41j/CasparCG%202.2.0.zip?dl=0)

**Comment by ronag** [comment]
@premultiply: Interlace mode fixed

[CasparCG 2.2.0](https://www.dropbox.com/s/9wh9wy6fn1tw41j/CasparCG%202.2.0.zip?dl=0)

**Comment by premultiply** [comment]
@ronag Clips with Multitrack Audio are playing now. Thanks!
But there still many files which are not playing at all. Please try the included testpattern files from https://github.com/CasparCG/Server/tree/2.1.0/deploy/general/server/media/TestPatterns first. Most of them do not play yet.
I think if they are playing correctly most of my other files will play too. And yes of course I can share them to you.

**Comment by dotarmin** [comment]
> But there are still many files which are not playing at all.

I'm experiencing the same issue with for example AMB.mp4.

**Comment by ronag** [comment]
The more files I have to test with the better.

@dotarmin AMB.mp4 works just fine for me. How do I reproduce?

**Comment by dotarmin** [comment]
> @ronag AMB.mp4 works just fine for me. How do I reproduce?

Version | Command | Video-mode | Channels | Consumers/channel 
------------ | ------------ | ------------- | ------------- | ------------
2.2.0 | play 1-10 amb loop | 1080i5000 | 2 | 1 x Decklink | No output

I have tried multiple AMB.mp4 files but non of them works. I have also tried this using the file extension as-well but I don't get any output. Trying same command with 2.10 works as expected. Tried also to skip the loop part but it didn't work!

**I missed that you uploaded a new version with interlace fixes etc. I will try out that version first.** I'll let you know if it works or not.

**Comment by dotarmin** [comment]
@ronag It works now with latest build. Really good job Robert!

**Comment by dotarmin** [comment]
@ronag A small thing we noticed but haven't verified yet is that we experience slightly longer latency when sending commands to the server from the client compared to 2.1.0. We'll look more into this but it would be great if somebody else also could look at this and verify it.

**Comment by ronag** [comment]
@dotarmin slightly longer latency? you need to be more specific than that :)

**Comment by ronag** [comment]
@premultiply it's a problem with streams that have no decoders. I will fix it together with some other stuff.

**Comment by dotarmin** [comment]
> slightly longer latency? you need to be more specific than that :) when? how much longer? how to reproduce?

Me and @5opr4ni looked at this and we experience the delay to be ~200ms  from the point the server receives the command until we see the first frame playing compared to 2.1.0. We used AMB as media file using video-mode 1080i5000.

Commands where sent using the CasparCG Client in both cases. I doesn't have to be something with this version of CG Server of course but we started to see this delay with this build. We have switched back and forth between 2.1.0 and 2.2.0 with same results as mentioned.

**Comment by ronag** [comment]
@dotarmin ok! I'll check

**Comment by 5opr4ni** [comment]
Should be 200ms lounger than 2.1

2.2 ~400 ms
2.1 ~200 ms

**Comment by 5opr4ni** [comment]
Longer not lounger. :)

**Comment by ronag** [comment]
I'm down to 100ms now. But it has some effects on buffering.

**Comment by dotarmin** [comment]
> I'm down to 80ms now. But it has some effects on buffering. Need to tune things a bit.

I don't know what to say! Amazing Robert! 🙇

**Comment by ronag** [comment]
New realease with lots of fixes.

[CasparCG 2.2.0](https://www.dropbox.com/s/9wh9wy6fn1tw41j/CasparCG%202.2.0.zip?dl=0)

**Comment by premultiply** [comment]
@ronag Well done!
All of my files are playing now.

On first quick impression there are only some little glitches left:
- Some files still freeze for a few moments on first field before they start playing
- Seeking does not work

How can I send you some of my (large) testfiles?

**Comment by ronag** [comment]
@premultiply Do you have dropbox, S3, amazon drive, gdrive or something similar?

> Some files still freeze for a few moments on first field before they start playing

Do you think you can record the DIAG window when you are experiencing this or send me the files?

> Seeking does not work

It should work. Can you provide files + AMCP commands?

**Comment by premultiply** [comment]
@ronag Ok, I will upload some of these files on tuesday (not in the office till tuesday).

**Comment by premultiply** [comment]
@ronag Sent you the file download links by mail.

My seeking tests where done with with normal CasparCG Client (next) with Seek-Values > 0.

If I use very small values (SEEK < 10) for seek parameter then it seeks to a far points in longrun (47 min) file. Increasing the seeks value by 1 it seeks to a point 7 minutes ahead in playback timeline.
So maybe this is (just) a value conversion problem in ffmpeg producer?

**Comment by ronag** [comment]
Manually merged with 8d7e06f49a0a35d686a5a3b3ea6db658eaf1ff5f

**Pull request closed without merging**
