### PR TITLE
WIP: [html] Upgrade to CEF3239 (Chromium 63)

### PR DESCRIPTION
**Pull request by Julusian**
Rebase #611 and #644 for 2.2.0

This upgrades the HTML producer to a more modern version of Chromium (CEF3239 / Chromium 63).

This builds on the work from @AndreasWilladsen and @sesse. Any additional tweaks or tests to run are appreciated. I have labelled this PR as a WIP as performance is not yet perfect and some frames appear to be being lost, however the same is true of the current version

Improvements:
- Newer chromium. Gives new features and makes template dev much easier at it matched current versions of chrome
- Font smoothing
- 3D CSS

Missing:
- WebGL (Pending [CEF #1006](https://bitbucket.org/chromiumembedded/cef/issues/1006))

### CODE REVIEW

**Comment by Julusian** [comment]
This isn't currently ready for merging until #692 is resolved as I suspect this might be missing some linux so files, as they were previously being included.

**Comment by Julusian** [comment]
@dotarmin @ronag I think I asked before but don't remember getting an answer, what are your thoughts on using a CEF build with proprietry_codecs enabled. This will give h264 and mp3 playback. Its disabled for royalty licensing reasons, but as we already support them via ffmpeg I don't see any issue there. #350

**Comment by Punkley** [comment]
I would also like to see propriety_codecs enabled, would make things a bit more functional.

Kingsley

**Comment by ronag** [comment]
@Julusian this doesn't build on windows :(

**Comment by ronag** [comment]
I'm reverting this until it does build.

**Comment by Julusian** [comment]
Thats odd. Im sure it did build the other day... Ill have a look this evening

**Comment by ronag** [comment]
@Julusian how's the windows libs going? The default builds won't work since the static link to runtime.

**Comment by Julusian** [comment]
I made a start on trying this out a couple of days ago and what I had built on windows, but I havent gotten around to checking it on linux yet, and there have been a lot of commits since so I ought to recheck it. 
Ill quickly check if it still builds and runs then raise another PR. I can deal with linux in another PR, unless you want it to be done in one?

**Comment by ronag** [comment]
Linux in another PR is perfect. I'm developing on Windows.

**Pull request merged**
