### PR TITLE
[protocol_amcp] Attempting to set MIXER BLEND or MIXER STRAIGHT_ALPHA_OUTPUT when disabled

### PR DESCRIPTION
**Pull request by Julusian**
#456

Attempting to set MIXER BLEND or MIXER STRAIGHT_ALPHA_OUTPUT when they are disabled in config now returns a 600 error, like the thumbnail commands.

### CODE REVIEW

**Comment by Julusian** [comment]
@ronag am I right in thinking that blend modes and straight alpha can't be disabled in the config now?

**Comment by ronag** [comment]
Nope. They can not.

**Comment by dotarmin** [comment]
> @ronag Nope. They can not.

But they're still available? 
How do we choose between premultiplied alpha and straight alpha by this?

/Armin

**Comment by ronag** [comment]
@dotarmin they should be enable by default. The reason they were possible to disable was because they used a OpenGL extension. However, since we now require OpenGL 4.5 that doesn't make sense anymore.

**Comment by dotarmin** [comment]
Thanks for clearing this out Robert! 👍

**Comment by jesperstarkar** [comment]
Just to clearify. It is the `mixer->straight_alpha` config that gets removed, and the `channel->straight_alpha_output` remains both as config and runtime mixer command?

Thank's for your help with this @Julusian. A shame it was a waste of your time.

**Comment by Julusian** [comment]
@jesperstarkar It would appear that straight alpha output has been removed completely. https://github.com/CasparCG/server/commit/947818a041fcb4f986adbe86f9b84531e471d0c1

**Comment by jesperstarkar** [comment]
Oh. That's not good. I look forward to seeing branches stabilise and start compiling a list of breaking changes to get an overview over functionality again.

**Comment by ronag** [comment]
> Oh. That's not good. I look forward to seeing branches stabilise and start compiling a list of breaking changes to get an overview over functionality again.

Please do!

**Comment by ronag** [comment]
> @jesperstarkar It would appear that straight alpha output has been removed completely. 947818a

It on my list to re-add. The implementation was very slow with both an extra render pass + a texture barrier which can cause problems on some setups.

**Comment by jesperstarkar** [comment]
@ronag My strategy is to start from the amcp-implementation, and then dive into producers/consumers to see what functions can be invoked or config.

**Comment by ronag** [comment]
@jesperstarkar yes, since a lot of people assume functionality in 2.1 that's been removed we decided to leave 2.1 as is and do a version bump.

**Pull request closed without merging**
