### PR TITLE
Support UYVY pixel format for DeckLink and NDI producer

### PR DESCRIPTION
**Pull request by ducthiem90**
Another way to do #1201

### CODE REVIEW

**Comment by ianshade** [comment]
Doesn't this upload the same data to the GPU twice?

**Comment by ducthiem90** [comment]
> Doesn't this upload the same data to the GPU twice?

Yes, but I think it does not problem

**Comment by Julusian** [comment]
> > Doesn't this upload the same data to the GPU twice?
>
> Yes, but I think it does not problem

I agree it would be better to avoid doing this, , but I dont think that is a blocking issue to this being merged

**Comment by Julusian** [comment]
Manually merged in 7b910c5cda7d9041105343695e391ab85344f3c9

**Pull request closed without merging**
