### PR TITLE
Fix NDI video stretched

### PR DESCRIPTION
**Pull request by jpc0**
This is a potential fix for https://github.com/CasparCG/server/issues/1542, unfortunately I cannot test on windows right now but it does work on linux with and without alpha and at multiple resolutions. Since I suspect there were no issues on windows I rather used an ifdef to not touch the code that runs on windows.

### CODE REVIEW

**Comment by Julusian** [comment]
This bug/fix confuses me, so I want to understand what is happening before merging. I won't be able to do that this week

**Comment by jpc0** [comment]
No problem it confuses me too.

The only reason I even though to use the stride in bytes is because in ffmpeg::make_frame the width is devided by the pixel stride for some reason.

In reality I am thinking about directly creating a casparcg frame from the libndi frame and avoiding the intermediate ffmpeg frame all together but I don't have time right now for such a refactor.

This is more a hacky solution that fixes the problem.

**Comment by jpc0** [comment]
If it helps at all. It is similarly broken on windows. Seems like something changed with NDI library sometime? I am reasonably certian this worked fine on 2.4.0 on release on windows since that was what I was running but with whatever NDI version was running then but when I run it now with the latest NDI it is in fact broken on windows as well. The same fix fixes the issue on linux as well,

**Comment by jpc0** [comment]
Some more testing. It work correctly on commit https://github.com/CasparCG/server/commit/55e3a04b8bc0aac89c0fea3b10458b38210d2e86 however at master it does not. 

It is a pain for me to bisect on my windows PC at home (CEF path fails to apply and AMD GPU BUG so need to apply 2 patches to codebase to get it to just build and run) so tomorrow I will try bisect on the linux box at work and hopefull get you to the exact commit that causes the break. I do suspect there was a change introduced when implementing HDR that broke it and I was running a custom build pre v2.4.0 on windows at work before.

**Comment by Julusian** [comment]
> I do suspect there was a change introduced when implementing HDR that broke it and I was running a custom build pre v2.4.0 on windows at work before.

Once you said it didn't work on windows either, I was wondering about this. Definitely plausible that it could have caused this. I wonder if a few ffmpeg codecs/formats could be affected too

**Comment by jpc0** [comment]
Looks like the commit that broke the behaviour is https://github.com/CasparCG/server/commit/e3289ecac25fca89221f258051222ecdefa08d92. I am happy to close this pull request if we can determine that there is actually other issues affecting ffmpeg but as is seen in the offending commit's change. Before we were referencing the linesize in ffmpeg::pixel_format_desc and after that commit we are referencing width.

I also found the release v2.4.0 is working correctly. So I cherry picked https://github.com/CasparCG/server/commit/e4e9ed299e1a0f9c87c8709d19b0585a5703102a ontop of the v2.4.0 tag and am running that

Two things I would like to see but if we want to open issues to make tracking them easier I'm happy to do that:
- The testing mentioned above, I will happily try to assist in implementation
- A v2.4 branch which only contains bugfixes and no new features. Semver effectively

**Comment by niklaspandersson** [comment]
I would really like to get some automated tests in place as well. After working on other codebases for a long time, it felt really shaky editing shared code without any kind of verification of correctness.

In theory it should be pretty easy to get some tests up and running considering the modular architecture, but my knowledge of build- and test tools for C++ are all but non-existing.

Ffmpeg has a separate setup script for the tests that download all required assets from a location separated from the repository. That might be a possible way to handle test videos for us as well

**Comment by Julusian** [comment]
We already have various build dependencies being fetched from releases in https://github.com/CasparCG/dependencies/ to avoid baking them into the repository, so it would be easy to add them there and get cmake to download them in the same way as the other dependencies when tests are wanted. 

I am open to having some tests, but I too don't know much about C++ test tooling. And I think it needs some thought on what the tests should be aiming to cover, especially as a lot of the bits that could do with tests have hardware/system requirements

**Comment by Julusian** [comment]
@jpc0 
> A v2.4 branch which only contains bugfixes and no new features. Semver effectively

There is https://github.com/CasparCG/server/tree/v2.4.x 

If you look at the version numbers of builds, the `master` branch identifies itself as `2.5.0-dev` currently.

On a related note, I should be thinking about tagging 2.4.1 at some point, but I haven't figured out the criteria for doing so.

**Comment by dimitry-ishenko** [comment]
> On a related note, I should be thinking about tagging 2.4.1 at some point, but I haven't figured out the criteria for doing so.

Yes please. If possible, I'd like to have my scaling mode PR and cef PR backported, so I can roll another Debian package... 😎

**Comment by niklaspandersson** [comment]
PR #1580 will hopefully resolve this issue without the duplicated code

**Pull request closed without merging**
