### PR TITLE
check for best videoquality before selecting stream

### PR DESCRIPTION
**Pull request by pkeuter**
This is a revised PR based on the latest changes in the 2.2.0 branch. This supersedes https://github.com/CasparCG/server/pull/696

### CODE REVIEW

**Comment by pkeuter** [comment]
To test the difference, try to play this stream: https://bitdash-a.akamaihd.net/content/MI201109210084_1/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8

Before: 
image

After: 
image

**Comment by ronag** [comment]
It should only do this if number of filter video inputs is equal to 1.

**Comment by pkeuter** [comment]
@ronag I've changed this now, although I don't really understand why. Can you explain?

**Comment by ronag** [comment]
Because if I have a alphamerge filter in my graph it should work as expected :)

**Comment by ronag** [comment]
It needs to go inside here https://github.com/pkeuter/Server/blob/8b988c9165c9d58c303aea289c463fcbb537c996/src/modules/ffmpeg/producer/av_producer.cpp#L212

**Comment by pkeuter** [comment]
@ronag, sure although that makes it necessary to  add a force_index flag. I've done that now, I assume this is what you mean? Else please elaborate.

**Comment by ronag** [comment]
Good enough.

**Pull request merged**
